Repository ProcessMaker/processmaker, pull requests merged in 2019-07, with the labels that each got.

#2018 new strings for translations
  resources/lang/en.json
Labels: conflicts

#2056 Variable Data Format Enhancements
  resources/lang/en.json
Labels: hold

#2123 Fix request file upload permissions
  ProcessMaker/Policies/ProcessRequestPolicy.php
  routes/api.php
  tests/Feature/Api/RequestFileUploadTest.php
  tests/Feature/Api/processes/FileUpload.bpmn
Labels: question

#2118 Update sanitizer so we can allow some tags from rich text input
  ProcessMaker/Http/Controllers/Api/TaskController.php
  ProcessMaker/Http/Middleware/SanitizeInput.php
  ProcessMaker/SanitizeHelper.php
  tests/Feature/Api/SanitizationTest.php
  tests/Feature/Api/TasksTest.php
  tests/Fixtures/rich_text_screen.json
  tests/Fixtures/single_task_with_screen.bpmn
  tests/bootstrap.php
Labels: hold
