Repository ProcessMaker/processmaker, pull requests merged in 2019-08, with the labels that each got.

#2145 Throw error if request was started by anonymous user and task is assigned to 'requestor'
  ProcessMaker/Exception/TaskDoesNotHaveRequesterException.php
  ProcessMaker/Models/Process.php
  resources/lang/en/exceptions.php
  tests/Feature/Api/IntermediateTimerEventTest.php
  tests/Feature/Processes/ScriptUserTaskTest.php
Labels: bug

#2212 Improvement/kr 7853
  .circleci/config.yml
  .env.dusk.testing
  ProcessMaker/Console/Commands/Install.php
  composer.json
  composer.lock
  database/migrations/2019_07_31_103534_add_process_key.php
  database/migrations/2019_07_31_103634_add_script_category.php
  database/migrations/2019_07_31_103652_add_screen_category.php
  database/migrations/2019_07_31_175014_create_script_categories.php
  tests/Browser/RequestsTest.php
  tests/DuskTestCase.php
Labels: Failing

#2342 Update user token list to use vuetable with pagination
  resources/js/admin/users/components/UserTokensListing.vue
  resources/js/admin/users/edit.js
  resources/views/admin/users/edit.blade.php
Labels: question
