Repository ProcessMaker/processmaker, pull requests merged in 2019-11, with the labels that each got.

#2500 Add node packages to about page
  ProcessMaker/Http/Controllers/AboutController.php
  resources/views/about/index.blade.php
Labels: review

#2525 BugFix: Add FormImage to Screen Builder Display-type
  resources/js/processes/screen-builder/typeDisplay.js
Labels: review

#2531 Update category permissions
  ProcessMaker/Http/Controllers/ProcessController.php
  ProcessMaker/Http/Middleware/GenerateMenus.php
  database/seeds/GroupSeeder.php
  database/seeds/PermissionSeeder.php
  resources/js/processes/categories/components/CategoriesListing.vue
  resources/views/categories/list.blade.php
  routes/api.php
  routes/web.php
  storage/api-docs/api-docs.json
  tests/Feature/Api/PermissionsTest.php
  tests/Feature/ProcessesTest.php
Labels: Failing, bug

#2577 UI improvements: search bar, element spacing, page width, notifications popover
  resources/js/components/Comments.vue
  resources/js/components/common/Pagination.vue
  resources/js/components/common/mixins/datatable.js
  resources/js/components/requests/modal.vue
  resources/js/components/requests/notifications.vue
  resources/js/requests/components/RequestDetail.vue
  resources/js/requests/components/RequestErrors.vue
  resources/js/requests/components/RequestScreens.vue
  resources/sass/app.scss
  resources/views/admin/auth-clients/index.blade.php
  resources/views/admin/groups/index.blade.php
  resources/views/admin/users/index.blade.php
  resources/views/categories/list.blade.php
  resources/views/components/categorized_resource.blade.php
  resources/views/notifications/index.blade.php
  resources/views/processes/environment-variables/index.blade.php
  resources/views/processes/list.blade.php
  resources/views/processes/screens/list.blade.php
  resources/views/processes/scripts/list.blade.php
  resources/views/requests/index.blade.php
  resources/views/requests/show.blade.php
  resources/views/tasks/edit.blade.php
  resources/views/tasks/editdata.blade.php
  resources/views/tasks/index.blade.php
Labels: review

#2587 Adds tooltip to warning icon on Process list
  resources/js/processes/components/ProcessesListing.vue
  resources/lang/en.json
Labels: review

#2582 Add default category
  database/seeds/CategorySystemSeeder.php
  database/seeds/DatabaseSeeder.php
Labels: refactor

#2588 Remove unneeded sections from Request detail screen
  resources/views/requests/show.blade.php
Labels: review

#2579 Implements Watchers (Form triggers)
  ProcessMaker/Http/Controllers/Api/DataSourcesController.php
  ProcessMaker/Http/Controllers/Api/ScreenController.php
  ProcessMaker/Http/Controllers/Api/ScriptController.php
  ProcessMaker/Http/Controllers/Process/ScreenBuilderController.php
  ProcessMaker/Jobs/ExecuteScript.php
  ProcessMaker/Models/DataSource.php
  ProcessMaker/Models/DataSourceCategory.php
  ProcessMaker/Models/Screen.php
  ProcessMaker/Notifications/ScriptResponseNotification.php
  ProcessMaker/ScriptRunners/Base.php
  ProcessMaker/Traits/MakeHttpRequests.php
  database/migrations/2019_09_28_191432_create_data_source_categories.php
  database/migrations/2019_09_30_191460_create_data_sources_table.php
  database/migrations/2019_11_05_143358_add_watcher_to_screens.php
  resources/js/processes/screen-builder/screen.vue
  resources/js/processes/screen-builder/typeForm.js
  resources/js/tasks/components/TaskForm.vue
  resources/lang/en.json
  resources/views/processes/screen-builder/screen.blade.php
  resources/views/tasks/edit.blade.php
  routes/api.php
  tests/Feature/Api/ScriptsTest.php
  tests/Feature/Api/WatchersTest.php
  tests/Feature/Docker/TimeoutsTest.php
Labels: Failing, bug

#2592 Edit Categories Modal
  ProcessMaker/Http/Controllers/Api/ScreenCategoryController.php
  ProcessMaker/Http/Controllers/Api/ScriptCategoryController.php
  ProcessMaker/Http/Controllers/Designer/ProcessCategoryController.php
  ProcessMaker/Http/Controllers/Process/ProcessCategoryController.php
  ProcessMaker/Http/Controllers/Process/ScreenCategoryController.php
  ProcessMaker/Http/Controllers/Process/ScreenController.php
  ProcessMaker/Http/Controllers/Process/ScriptCategoryController.php
  ProcessMaker/Http/Controllers/Process/ScriptController.php
  ProcessMaker/Http/Controllers/ProcessController.php
  ProcessMaker/Models/ScreenCategory.php
  resources/js/processes/categories/components/CategoriesListing.vue
  resources/js/processes/categories/index.js
  resources/lang/en.json
  resources/views/categories/edit.blade.php
  resources/views/categories/list.blade.php
  routes/web.php
  tests/Feature/Api/ScreenCategoriesTest.php
  tests/Feature/Api/ScriptCategoriesTest.php
Labels: bug, conflicts, refactor
