Repository ProcessMaker/processmaker, pull requests merged in 2019-05, with the labels that each got.

#1779 Update tasks list index
  ProcessMaker/Http/Controllers/Api/TaskController.php
Labels: WIP

#1767 Update modeler
  package-lock.json
  package.json
  resources/js/bootstrap.js
  resources/js/processes/modeler/components/ModelerApp.vue
  resources/js/processes/screen-builder/main.js
  resources/js/processes/screen-builder/screen.vue
  tests/Browser/ScreenTest.php
Labels: review

#1736 Fix cancel action
  ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
  ProcessMaker/Jobs/CancelRequest.php
  resources/views/requests/show.blade.php
  tests/Feature/Api/ProcessRequestsTest.php
Labels: Failing

#1785 Fix request task list
  ProcessMaker/Http/Controllers/Api/TaskController.php
  resources/js/tasks/components/TasksList.vue
Labels: review

#1787 Fix category show create new
  resources/js/processes/categories/components/CategoriesListing.vue
Labels: WIP

#1801 Fix cancel status
  ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
  ProcessMaker/Jobs/CancelRequest.php
Labels: review

#1744 Add info for loading, no results, and errors to vuetable
  package-lock.json
  resources/js/app-layout.js
  resources/js/components/common/DataLoading.vue
  resources/js/components/common/mixins/apiDataLoading.js
  resources/js/requests/components/RequestsListing.vue
  resources/js/tasks/components/TasksList.vue
Labels: testing only

#1806 Importing Process Without Required Package
  ProcessMaker/Jobs/ImportProcess.php
  ProcessMaker/Managers/PackageManager.php
  ProcessMaker/Providers/ProcessMakerServiceProvider.php
  ProcessMaker/Traits/PluginServiceProviderTrait.php
  resources/js/processes/modeler/components/inspector/ScreenSelect.vue
  resources/views/processes/import.blade.php
Labels: conflicts

#1825 Fix exception message for empty script tasks
  ProcessMaker/Jobs/RunScriptTask.php
Labels: review

#1872 Preview Inspector uses full height
  resources/js/processes/screen-builder/screen.vue
Labels: review

#1883 Set preview display to the form first
  resources/js/processes/screen-builder/screen.vue
Labels: review
