Repository ProcessMaker/processmaker, pull requests merged in 2020-03, with the labels that each got.

#2907 Fix Watcher 'Source' selection limit
  resources/views/processes/screen-builder/screen.blade.php
Labels: review

#2919 Fix Environment Variable Text Limit
  database/migrations/2020_03_03_181316_update_env_var_value_column.php
  resources/views/processes/environment-variables/index.blade.php
Labels: review

#2916 Display nested data summary as a flat list
  resources/js/requests/components/DataSummary.vue
  resources/js/requests/show.js
  resources/views/requests/show.blade.php
Labels: review

#2918 Disallow dashes in Environment Variable Names
  ProcessMaker/Http/Controllers/Api/EnvironmentVariablesController.php
  ProcessMaker/Models/EnvironmentVariable.php
  resources/lang/en/environmentVariables.php
Labels: review

#2929 Fix Assign by Expression User ID
  ProcessMaker/Models/Process.php
  resources/js/processes/modeler/components/inspector/TaskAssignment.vue
Labels: review

#2946 User/Group ID Column
  resources/js/admin/groups/components/GroupsListing.vue
  resources/js/admin/groups/components/UsersInGroupListing.vue
  resources/js/admin/users/components/DeletedUsersListing.vue
  resources/js/admin/users/components/UsersListing.vue
Labels: review

#2944 Add missing Asterisks
  resources/views/admin/groups/edit.blade.php
  resources/views/processes/screens/edit.blade.php
Labels: review

#2945 Hide usernames & passwords in ENV
  config/app.php
Labels: review

#2953 API Doc Link
  resources/js/processes/scripts/components/ScriptEditor.vue
  resources/js/processes/scripts/customFilters.js
Labels: review

#2950 Fix file download editor-control
  resources/js/processes/screen-builder/components/file-download-control.js
Labels: review

#2986 Fix About Page fails without node_modules
  ProcessMaker/Http/Controllers/AboutController.php
Labels: review

#2981 Fix PMQL Not Equals returning Equals
  ProcessMaker/Models/ProcessRequest.php
  ProcessMaker/Models/ProcessRequestToken.php
Labels: conflicts, review

#2955 Remove task config override
  resources/js/processes/modeler/initialLoad.js
Labels: dependencies, hold
