Repository ProcessMaker/processmaker, pull requests merged in 2023-05, with the labels that each got.

#4698 Bugfix/FOUR-6473: As a process designer, I want to be able to index fields in JSON data
  ProcessMaker/JsonColumnIndex.php
  ProcessMaker/Traits/ExtendedPMQL.php
  ProcessMaker/Traits/Indexable.php
  ProcessMaker/Upgrades/UpgradeMigrator.php
  stubs/upgrades/migration.stub
  tests/unit/ProcessMaker/JsonColumnIndexTest.php
Labels: codeball:needs-careful-review

#4731 FOUR-8308: Enabling the "Edit Decision Table Categories" permission for a no admin user doesn't work
  resources/js/components/shared/EllipsisMenu.vue
Labels: codeball:needs-careful-review

#4735 FOUR-8342 Duplicate media queries
  ProcessMaker/Console/Commands/PopulateAvatarColumn.php
  ProcessMaker/Http/Controllers/Api/UserController.php
  ProcessMaker/Models/User.php
  database/migrations/2023_05_03_131855_add_avatar_to_users_table.php
  upgrades/2023_05_03_131855_add_avatar_to_users_table.php
Labels: codeball:needs-careful-review

#4730 FOUR-8349 Add index to order_column in media table
  database/migrations/2023_05_02_183152_add_order_column_index_to_media_table.php
  tests/unit/ProcessMaker/MediaOrderColumnIndexTest.php
Labels: codeball:needs-careful-review

#4732 Add indexes to process_request_tokens
  database/migrations/2023_05_02_184218_add_indexes_to_process_request_tokens.php
Labels: codeball:needs-careful-review

#4736 Fix 'API Failed' flash on Task List load
  resources/js/tasks/components/TasksList.vue
Labels: codeball:approved

#4729 Allow exporting when models are missing
  ProcessMaker/Http/Controllers/Api/ExportController.php
  ProcessMaker/ImportExport/Exporters/ExporterBase.php
  ProcessMaker/ImportExport/Exporters/ProcessExporter.php
  ProcessMaker/ImportExport/Exporters/ScreenExporter.php
Labels: codeball:needs-careful-review

#4725 Bugfix/FOUR-8333: The search by numeral digits, is changed to code on the screen
  resources/js/components/shared/GlobalSearch.vue
Labels: codeball:needs-careful-review

#4728 Bugfix/FOUR-8359: Template Details Modal UI Adjustments
  resources/js/components/templates/TemplateDetails.vue
Labels: codeball:approved

#4734 FOUR-8391 - Get right number of overdue tasks
  ProcessMaker/Http/Controllers/Api/TaskController.php
  database/factories/ProcessMaker/Models/ProcessRequestTokenFactory.php
  resources/js/tasks/components/TasksList.vue
  resources/js/tasks/index.js
  resources/views/tasks/index.blade.php
  tests/Feature/Api/TasksTest.php
Labels: codeball:needs-careful-review

#4738 FOUR-8430 - Trigger save event on Script Editor focusout
  resources/js/processes/modeler/components/inspector/ConfigEditor.vue
Labels: codeball:approved

#4737 Check if user exists before adding dependent
  ProcessMaker/ImportExport/Exporters/ProcessExporter.php
Labels: codeball:approved

#4720 Bugfix/four 8091
  resources/js/components/shared/EllipsisMenu.vue
  resources/js/components/templates/CreateTemplateModal.vue
  resources/lang/de.json
  resources/lang/en.json
  resources/lang/es.json
  resources/lang/fr.json
Labels: codeball:needs-careful-review

#4724 Fix failing PHP unit tests
  ProcessMaker/Jobs/ImportProcess.php
  tests/TestCase.php
Labels: codeball:needs-careful-review

#4749 Translate strings automatically using GPT-4
  .github/workflows/scripts/translate.py
  .github/workflows/translate_strings.yml
Labels: codeball:needs-careful-review

#4745 FOUR-8446 - Trigger autosave when clicking Close
  resources/js/leave-warning.js
  resources/js/modules/autosave/autosaveMixin.js
  resources/js/modules/autosave/closeMixin.js
  resources/js/modules/autosave/mixins.js
  resources/js/processes/modeler/components/ModelerApp.vue
  resources/js/processes/screen-builder/screen.vue
  resources/js/processes/scripts/components/ScriptEditor.vue
  resources/views/processes/scripts/builder.blade.php
Labels: codeball:needs-careful-review

#4743 Fix url matchers for loading screen
  resources/js/processes/components/ProcessesListing.vue
  resources/js/templates/components/ProcessTemplatesListing.vue
Labels: codeball:needs-review

#4760 Update default interstitial design
  database/processes/screens/interstitial.json
Labels: codeball:needs-review

#4742 Add 'Vendor Onboarding' default template
  ProcessMaker/Templates/Fixtures/process-vendor-onboarding-template.json
  ProcessMaker/Templates/Fixtures/process-vendor-onboarding.svg
  database/migrations/2023_05_04_181453_add_vendor_on_boarding_in_process_templates_table.php
  database/seeders/ProcessTemplatesSeeder.php
Labels: codeball:needs-review

#4762 Additional translations for Templates
  resources/js/processes/import/components/ImportManagerView.vue
  resources/lang/en.json
Labels: codeball:needs-careful-review

#4766 Automated Translations Updates
  .github/workflows/scripts/translate.py
  .github/workflows/translate_strings.yml
Labels: codeball:needs-careful-review

#4765 Added IDP translations
  resources/lang/en.json
Labels: codeball:approved

#4769 Add missing translations
  resources/lang/en.json
Labels: codeball:needs-careful-review

#4771 Screen Builder v2.71.3
  package-lock.json
  package.json
Labels: codeball:approved

#4772 v4.6.0-RC8 updates to enterprise & custom packages
  composer.json
Labels: codeball:approved

#4773 Apply changes for patch 2 (4.3.0-patch-2-les-schwab): performance improvements, node ssr, previous patch changes,
  .github/workflows/codeball.yml
  ProcessMaker/Console/Commands/PopulateAvatarColumn.php
  ProcessMaker/Console/Commands/SeedPerformanceData.php
  ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
  ProcessMaker/Http/Controllers/Api/TaskController.php
  ProcessMaker/Http/Controllers/Api/UserController.php
  ProcessMaker/Models/Comment.php
  ProcessMaker/Models/ProcessRequest.php
  ProcessMaker/Models/ProcessRequestLock.php
  ProcessMaker/Models/RequestUserPermission.php
  ProcessMaker/Models/SecurityLog.php
  ProcessMaker/Models/User.php
  ProcessMaker/Policies/ProcessRequestPolicy.php
  ProcessMaker/Traits/ForUserScope.php
  database/factories/ProcessMaker/Models/ProcessRequestFactory.php
  database/migrations/2022_12_15_014415_add_is_self_service_index_to_process_request_tokens_table.php
  database/migrations/2023_05_02_183152_add_order_column_index_to_media_table.php
  database/migrations/2023_05_02_184218_add_indexes_to_process_request_tokens.php
  database/migrations/2023_05_03_131855_add_avatar_to_users_table.php
  tests/Feature/Api/ProcessExecutionTest.php
  tests/Feature/Api/ProcessManualTaskTest.php
  tests/Feature/Api/ProcessRequestPolicyTest.php
  tests/Feature/Api/ServiceTaskExecutionTest.php
  tests/Feature/OnSiteStorage/ExternalConnectionTest.php
  tests/Feature/Shared/RequestHelper.php
  tests/Performance/RequestListingPerformanceData.php
  tests/Performance/RequestListingPerformanceTest.php
  tests/TestCase.php
  tests/Traits/ForUserScopeTest.php
  tests/unit/ProcessMaker/MediaOrderColumnIndexTest.php
  upgrades/2023_05_03_131855_add_avatar_to_users_table.php
Labels: codeball:needs-careful-review

#4788 Draft: API for security log
  ProcessMaker/Contracts/SecurityLogEventInterface.php
  ProcessMaker/Events/ProcessCreated.php
  ProcessMaker/Events/SettingsUpdated.php
  ProcessMaker/Helpers/SensitiveDataHelper.php
  ProcessMaker/Http/Controllers/Api/SecurityLogController.php
  ProcessMaker/Http/Controllers/Api/SettingController.php
  ProcessMaker/Http/Resources/SecurityLogs.php
  ProcessMaker/Listeners/SecurityLogger.php
  ProcessMaker/Models/SecurityLog.php
  ProcessMaker/Providers/EventServiceProvider.php
  ProcessMaker/Traits/FormatSecurityLogChanges.php
  database/migrations/2023_05_10_143850_add_iso27001_columns_for_security_logs_table.php
  resources/lang/en/validation.php
  routes/api.php
  tests/Feature/Api/SecurityLogsTest.php
  tests/unit/ProcessMaker/Helpers/SensitiveDataHelperTest.php
Labels: codeball:needs-review

#4801 Modeler v1.30.2
  package-lock.json
  package.json
Labels: codeball:approved

#4807 Store all changes for internal use
  ProcessMaker/Contracts/SecurityLogEventInterface.php
  ProcessMaker/Events/SettingsUpdated.php
  ProcessMaker/Listeners/SecurityLogger.php
  ProcessMaker/Models/SecurityLog.php
  ProcessMaker/Traits/FormatSecurityLogChanges.php
  database/migrations/2023_05_22_161025_add_changes_column_to_security_logs_table.php
Labels: codeball:needs-review

#4810 FOUR-8266: Log user, group and environments variables
  ProcessMaker/Events/EnvironmentVariablesCreated.php
  ProcessMaker/Events/EnvironmentVariablesDeleted.php
  ProcessMaker/Events/EnvironmentVariablesUpdated.php
  ProcessMaker/Events/GroupCreated.php
  ProcessMaker/Events/GroupDeleted.php
  ProcessMaker/Events/UserCreated.php
  ProcessMaker/Events/UserDeleted.php
  ProcessMaker/Http/Controllers/Api/EnvironmentVariablesController.php
  ProcessMaker/Http/Controllers/Api/GroupController.php
  ProcessMaker/Http/Controllers/Api/UserController.php
  ProcessMaker/Providers/EventServiceProvider.php
Labels: codeball:needs-careful-review

#4816 FOUR-8229 Log Unauthorized access attempts
  ProcessMaker/Events/UnauthorizedAccessAttempt.php
  ProcessMaker/Exception/Handler.php
  ProcessMaker/Providers/EventServiceProvider.php
  tests/Feature/Api/SecurityLogsTest.php
Labels: codeball:needs-review

#4793 FOUR-8233: changes in Tokens
  ProcessMaker/Events/TokenCreated.php
  ProcessMaker/Events/TokenDeleted.php
  ProcessMaker/Http/Controllers/Api/UserTokenController.php
  ProcessMaker/Providers/EventServiceProvider.php
Labels: codeball:needs-careful-review

#4812 FOUR-8248: Log changes to designer script
  ProcessMaker/Events/ScriptCreated.php
  ProcessMaker/Events/ScriptDeleted.php
  ProcessMaker/Events/ScriptDuplicated.php
  ProcessMaker/Events/ScriptUpdated.php
  ProcessMaker/Events/SettingsUpdated.php
  ProcessMaker/Helpers/SensitiveDataHelper.php
  ProcessMaker/Http/Controllers/Api/ScriptController.php
  ProcessMaker/Providers/EventServiceProvider.php
Labels: codeball:needs-careful-review

#4785 FOUR-8231
  ProcessMaker/Events/GroupUsersUpdated.php
  ProcessMaker/Events/UserGroupMembershipUpdated.php
  ProcessMaker/Http/Controllers/Api/GroupMemberController.php
  ProcessMaker/Http/Controllers/Api/UserController.php
  ProcessMaker/Providers/EventServiceProvider.php
Labels: codeball:needs-careful-review

#4819 FOUR-8257
  ProcessMaker/Events/ScriptExecutorCreated.php
  ProcessMaker/Events/ScriptExecutorDeleted.php
  ProcessMaker/Events/ScriptExecutorUpdated.php
  ProcessMaker/Http/Controllers/Api/ScriptExecutorController.php
  ProcessMaker/Providers/EventServiceProvider.php
Labels: codeball:needs-careful-review

#4821 FOUR-8242
  ProcessMaker/Events/CustomizeUiUpdated.php
  ProcessMaker/Http/Controllers/Api/CssOverrideController.php
  ProcessMaker/Providers/EventServiceProvider.php
Labels: codeball:needs-review

#4789 FOUR-8527 - Visualize the Process Map
  ProcessMaker/Http/Controllers/Process/ModelerController.php
  resources/js/process-map-layout.js
  resources/js/processes/modeler/components/ProcessMap.vue
  resources/js/processes/modeler/process-map.js
  resources/js/requests/show.js
  resources/js/tasks/show.js
  resources/views/layouts/process-map.blade.php
  resources/views/processes/modeler/inflight.blade.php
  resources/views/requests/show.blade.php
  routes/web.php
  webpack.mix.js
Labels: codeball:needs-careful-review

#4808 Show message and assign default server for missing reference
  ProcessMaker/Http/Controllers/Api/ImportController.php
  resources/js/app-layout.js
  resources/js/components/Message.vue
  resources/js/processes/import/components/ImportManagerView.vue
  resources/views/layouts/navbar.blade.php
Labels: codeball:needs-careful-review

#4805 Use subquery instead of passing in list of IDs
  ProcessMaker/Models/ProcessRequest.php
  tests/Feature/Api/ProcessRequestsTest.php
Labels: codeball:approved

#4804 Use mysql equals operator when matching numbers
  ProcessMaker/Http/Controllers/Api/TaskController.php
  tests/Feature/Api/TasksTest.php
Labels: codeball:approved
