Repository ProcessMaker/processmaker, pull requests merged in 2023-04, with the labels that each got.

#4662 FOUR-7766 - Script with Draft status can be added in a Watcher. Then an error occurs
  ProcessMaker/Http/Controllers/Process/ScriptController.php
  resources/js/components/Menu.vue
  resources/js/processes/scripts/components/ScriptEditor.vue
  resources/views/processes/scripts/builder.blade.php
Labels: codeball:needs-review

#4661 FOUR-7763 - Indicator is not displayed if a asset has draft or publish status
  resources/js/components/Menu.vue
  resources/js/processes/scripts/components/ScriptEditor.vue
Labels: codeball:needs-careful-review

#4642 FOUR-7637 | Ellipsis Menu
  package-lock.json
  package.json
  resources/js/components/shared/EllipsisMenu.vue
  resources/js/components/shared/index.js
  resources/js/processes/components/ProcessesListing.vue
  resources/sass/app.scss
Labels: codeball:needs-careful-review

#4635 FOUR-6105 As a Solutions Designer, I want to remove elements from the UI so that my custom solution can feel and operate distinctly from ProcessMaker’s standard functionality
  helpers.php
  resources/js/components/requests/notifications.vue
  resources/views/layouts/layout.blade.php
  resources/views/layouts/navbar.blade.php
  resources/views/requests/show.blade.php
  resources/views/shared/breadcrumbs.blade.php
  resources/views/tasks/edit.blade.php
Labels: codeball:needs-careful-review

#4667 Branding Update 2023
  ProcessMaker/Http/Controllers/AboutController.php
  composer.json
  config/app.php
  public/favicon.png
  resources/img/avatar-overlay-blank.png
  resources/img/avatar-placeholder.gif
  resources/img/avatar-profile-overlay.png
  resources/img/avatar.png
  resources/img/avatar_placeholder_small.png
  resources/img/dottedArrow.png
  resources/img/favicon.ico
  resources/img/favicon.svg
  resources/img/icon-pmlogo.png
  resources/img/lg-blk-logo.png
  resources/img/lg-blue-logo.png
  resources/img/lg-icon.png
  resources/img/lg-wht-logo.png
  resources/img/logo.png
  resources/img/md-blk-logo.png
  resources/img/md-icon.png
  resources/img/md-wht-logo.png
  resources/img/processmaker-icon-white-sm.png
  resources/img/processmaker-icon.svg
  resources/img/processmaker-login-logo.png
  resources/img/processmaker-login.svg
  resources/img/processmaker-logo.svg
  resources/img/processmaker_fulllogo_white-md.png
  resources/img/processmaker_icon.png
  resources/img/processmaker_login.png
  resources/img/processmaker_logo.png
  resources/img/processmaker_logo_white.jpg
  resources/img/sm-blk-logo.png
  resources/img/sm-blue-logo.png
  resources/img/sm-icon.png
  resources/img/sm-wht-icon.png
  resources/img/sm-wht-logo.png
  resources/lang/en.json
  resources/views/about/index.blade.php
Labels: codeball:needs-careful-review

#4668 Fix image issues
  public/img/avatar.png
  public/img/dataTable.png
  public/img/dottedArrow.png
  public/img/icon-pmlogo.png
  public/img/logo.png
  public/img/processmaker_logo_white.jpg
  resources/js/components/shared/GlobalSearch.vue
Labels: codeball:needs-careful-review

#4659 Import/Export updates for dependent select list
  ProcessMaker/ImportExport/Utils.php
  tests/Feature/ImportExport/UtilsTest.php
Labels: codeball:needs-review

#4652 AutoSave
  .eslintrc.js
  .gitignore
  ProcessMaker/Console/Commands/CreateDataLakeViews.php
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/Api/ScreenController.php
  ProcessMaker/Http/Controllers/Api/ScriptController.php
  ProcessMaker/Http/Controllers/Process/ModelerController.php
  ProcessMaker/Http/Controllers/Process/ScreenBuilderController.php
  ProcessMaker/Http/Controllers/Process/ScriptController.php
  ProcessMaker/Models/Process.php
  ProcessMaker/Models/ProcessRequestToken.php
  ProcessMaker/Models/ProcessVersion.php
  ProcessMaker/Models/ScreenVersion.php
  ProcessMaker/Models/ScriptExecutorVersion.php
  ProcessMaker/Models/ScriptVersion.php
  ProcessMaker/PackageHelper.php
  ProcessMaker/Providers/EventServiceProvider.php
  ProcessMaker/Traits/HasVersioning.php
  database/migrations/2023_02_27_130520_add_draft_column_to_versions_tables.php
  database/migrations/2023_03_13_172619_create_data_lake_views.php
  resources/js/components/Menu.vue
  resources/js/processes/modeler/components/ModelerApp.vue
  resources/js/processes/screen-builder/screen.vue
  resources/js/processes/scripts/components/ScriptEditor.vue
  resources/views/processes/modeler/index.blade.php
  resources/views/processes/screen-builder/screen.blade.php
  resources/views/processes/scripts/builder.blade.php
  routes/api.php
  tests/Feature/Api/ProcessTest.php
  tests/Feature/Api/ScreenTest.php
  tests/Feature/Api/ScriptsTest.php
Labels: codeball:needs-careful-review

#4664 Create Default Templates
  ProcessMaker/Templates/Fixtures/process-employee-onboarding-template.json
  ProcessMaker/Templates/Fixtures/process-leave-of-absence-template.json
  ProcessMaker/Templates/Fixtures/process-leave-of-absence-template.svg
  ProcessMaker/Templates/ProcessTemplate.php
  database/migrations/2023_03_09_023511_create_process_templates_table.php
  database/migrations/2023_04_07_211608_add_seeded_data_to_process_templates.php
  database/seeders/ProcessTemplatesSeeder.php
  resources/js/components/shared/Modal.vue
  resources/js/components/templates/CreateTemplateModal.vue
  resources/js/components/templates/TemplateDetails.vue
  resources/js/components/templates/TemplateSearch.vue
  resources/js/components/templates/TemplateSelectCard.vue
  tests/Feature/ImportExport/Api/ExportImportTest.php
  tests/Feature/Templates/Api/ProcessTemplateTest.php
Labels: codeball:needs-careful-review

#4673 Process Templates: Edit Process Template in Modeler
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/Api/TemplateController.php
  ProcessMaker/Models/Template.php
  ProcessMaker/Templates/ProcessTemplate.php
  ProcessMaker/Templates/TemplateInterface.php
  database/migrations/2023_04_06_002637_add_is_template_column_to_specific_tables.php
  resources/js/processes/modeler/components/ModelerApp.vue
  routes/api.php
Labels: codeball:needs-careful-review

#4670 FOUR-7854: Fix Ellipse styling for Process Templates
  resources/js/templates/components/ProcessTemplatesListing.vue
Labels: codeball:needs-careful-review

#4675 FOUR-7912: Remove the author avatar for Default Templates
  ProcessMaker/Templates/ProcessTemplate.php
  resources/js/components/AvatarImage.vue
  resources/js/templates/components/ProcessTemplatesListing.vue
Labels: codeball:needs-careful-review

#4674 FOUR-7913: Fix issue with template data not persisting after second use
  resources/js/components/templates/SelectTemplateModal.vue
  resources/js/processes/components/CreateProcessModal.vue
Labels: codeball:needs-review

#4681 FOUR-7869 Allows to show/hide the global search bar from the menu for Dynamic UI
  config/app.php
  resources/views/layouts/navbar.blade.php
Labels: codeball:needs-review

#4682 Prevent duplicate categories when using default templates
  ProcessMaker/Templates/Fixtures/process-employee-onboarding-template.json
  ProcessMaker/Templates/Fixtures/process-leave-of-absence-template.json
  ProcessMaker/Templates/ProcessTemplate.php
Labels: codeball:needs-careful-review

#4685 Process Templates
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/Api/TemplateController.php
  ProcessMaker/Http/Controllers/TemplateController.php
  ProcessMaker/Http/Middleware/TemplateAuthorization.php
  ProcessMaker/ImportExport/Exporters/ExporterBase.php
  ProcessMaker/ImportExport/Exporters/ProcessExporter.php
  ProcessMaker/ImportExport/Importer.php
  ProcessMaker/ImportExport/Manifest.php
  ProcessMaker/ImportExport/Options.php
  ProcessMaker/Models/Template.php
  ProcessMaker/Repositories/TokenRepository.php
  ProcessMaker/Templates/Fixtures/process-employee-onboarding-template.json
  ProcessMaker/Templates/Fixtures/process-leave-of-absence-template.json
  ProcessMaker/Templates/Fixtures/process-leave-of-absence-template.svg
  ProcessMaker/Templates/ProcessTemplate.php
  ProcessMaker/Templates/TemplateInterface.php
  ProcessMaker/Traits/HideSystemResources.php
  database/factories/ProcessMaker/Models/ProcessTemplatesFactory.php
  database/migrations/2023_03_09_023511_create_process_templates_table.php
  database/migrations/2023_04_06_002637_add_is_template_column_to_specific_tables.php
  database/migrations/2023_04_07_211608_add_seeded_data_to_process_templates.php
  database/seeders/ProcessTemplatesSeeder.php
  resources/js/components/AvatarImage.vue
  resources/js/components/shared/Modal.vue
  resources/js/components/templates/CreateTemplateModal.vue
  resources/js/components/templates/SelectTemplateModal.vue
  resources/js/components/templates/TemplateDetails.vue
  resources/js/components/templates/TemplateSearch.vue
  resources/js/components/templates/TemplateSelectCard.vue
  resources/js/processes/components/CreateProcessModal.vue
  resources/js/processes/export/state.js
  resources/js/processes/import/components/ImportManagerView.vue
  resources/js/processes/modeler/components/ModelerApp.vue
  resources/js/templates/components/ProcessTemplatesListing.vue
  resources/views/processes/modeler/showTemplate.blade.php
  routes/api.php
  routes/web.php
  tests/Feature/Api/TaskAssignmentByVariableTest.php
  tests/Feature/ImportExport/Api/ExportImportTest.php
  tests/Feature/Templates/Api/ProcessTemplateTest.php
Labels: codeball:needs-careful-review

#4683 FOUR-7920 - Modeler Toolbar Improvements
  resources/js/components/shared/EllipsisMenu.vue
Labels: codeball:approved

#4686 Merge last changes in feature branch FOUR-6105 to develop
  config/app.php
  resources/views/layouts/navbar.blade.php
Labels: codeball:needs-careful-review

#4676 FOUR-7891 - Profile Edit Permission
  database/seeders/PermissionSeeder.php
  resources/js/components/NavbarProfile.vue
  resources/views/layouts/navbar.blade.php
  routes/web.php
  tests/Feature/ProfileTest.php
Labels: codeball:needs-review

#4691 Feature/FOUR-8051
  ProcessMaker/Traits/ExtendedPMQL.php
Labels: codeball:needs-review

#4688 It is possible to import a process in the templates tab
  ProcessMaker/Http/Controllers/Api/ImportController.php
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/Api/TemplateController.php
  resources/js/components/shared/DraggableFileUpload.vue
  resources/js/processes/export/DataProvider.js
  resources/js/processes/import/components/ImportManagerView.vue
  routes/api.php
Labels: codeball:needs-careful-review

#4695 [FOUR-8126] Recompiling Mix fails on instance when colors have been customized
  resources/js/admin/cssOverride/components/SiteDesign.vue
  resources/sass/_colors.scss
  resources/sass/_variables.scss
Labels: codeball:needs-review

#4692 Add Expense Approval default template
  ProcessMaker/Templates/Fixtures/process-expense-approval.json
  ProcessMaker/Templates/Fixtures/process-expense-approval.svg
  database/migrations/2023_04_20_181405_add_expense_approval_default_template_to_process_templates.php
  database/seeders/ProcessTemplatesSeeder.php
Labels: codeball:needs-careful-review

#4684 FOUR-7955 | Implement the New Ellipsis Menu for Specified Menus Across the Platform
  resources/js/processes/screens/components/ScreenListing.vue
  resources/js/processes/scripts/components/ScriptListing.vue
  resources/js/tasks/components/TasksList.vue
Labels: codeball:needs-careful-review

#4694 Integrate Ellipses Menu pt1
  package-lock.json
  resources/js/admin/auth-clients/components/AuthClientsListing.vue
  resources/js/admin/groups/components/GroupsListing.vue
  resources/js/admin/users/components/UsersListing.vue
  resources/js/components/shared/EllipsisMenu.vue
  resources/js/processes/categories/components/CategoriesListing.vue
  resources/js/processes/components/ProcessesListing.vue
  resources/js/processes/environment-variables/components/VariablesListing.vue
  resources/js/processes/screens/components/ScreenListing.vue
  resources/js/processes/scripts/components/ScriptListing.vue
  resources/js/tasks/components/TasksList.vue
  resources/js/templates/components/ProcessTemplatesListing.vue
Labels: codeball:needs-careful-review

#4696 Fix processes created from template not being listed
  ProcessMaker/Templates/ProcessTemplate.php
Labels: codeball:needs-careful-review

#4693 Update title and description of the current default templates
  ProcessMaker/Templates/Fixtures/process-employee-onboarding-template.json
  ProcessMaker/Templates/Fixtures/process-employee-onboarding-template.svg
  ProcessMaker/Templates/Fixtures/process-leave-of-absence-template.json
  ProcessMaker/Templates/Fixtures/process-leave-of-absence-template.svg
  database/migrations/2023_04_20_194205_update_leave_of_absence_and_new_hire_onboarding_templates.php
  database/seeders/ProcessTemplatesSeeder.php
  tests/Feature/Templates/Api/ProcessTemplateTest.php
Labels: codeball:needs-careful-review

#4700 Update CI/CD Info in Readme
  README.md
Labels: codeball:needs-careful-review

#4701 Preparation for 4.6.0-RC5
  resources/sass/app.scss
Labels: codeball:needs-careful-review

#4704 Process Templates
  ProcessMaker/Http/Controllers/Api/ImportController.php
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/Api/TemplateController.php
  ProcessMaker/Templates/Fixtures/process-employee-onboarding-template.json
  ProcessMaker/Templates/Fixtures/process-employee-onboarding-template.svg
  ProcessMaker/Templates/Fixtures/process-expense-approval.json
  ProcessMaker/Templates/Fixtures/process-expense-approval.svg
  ProcessMaker/Templates/Fixtures/process-leave-of-absence-template.json
  ProcessMaker/Templates/Fixtures/process-leave-of-absence-template.svg
  ProcessMaker/Templates/ProcessTemplate.php
  database/migrations/2023_04_20_181405_add_expense_approval_default_template_to_process_templates.php
  database/migrations/2023_04_20_194205_update_leave_of_absence_and_new_hire_onboarding_templates.php
  database/seeders/ProcessTemplatesSeeder.php
  package-lock.json
  resources/js/admin/auth-clients/components/AuthClientsListing.vue
  resources/js/admin/groups/components/GroupsListing.vue
  resources/js/admin/users/components/UsersListing.vue
  resources/js/components/shared/DraggableFileUpload.vue
  resources/js/components/shared/EllipsisMenu.vue
  resources/js/components/templates/TemplateDetails.vue
  resources/js/processes/categories/components/CategoriesListing.vue
  resources/js/processes/components/ProcessesListing.vue
  resources/js/processes/environment-variables/components/VariablesListing.vue
  resources/js/processes/export/DataProvider.js
  resources/js/processes/import/components/ImportManagerView.vue
  resources/js/processes/screens/components/ScreenListing.vue
  resources/js/processes/scripts/components/ScriptListing.vue
  resources/js/tasks/components/TasksList.vue
  resources/js/templates/components/ProcessTemplatesListing.vue
  routes/api.php
  tests/Feature/Templates/Api/ProcessTemplateTest.php
Labels: codeball:needs-careful-review

#4697 Bugfix: recent-search request triggering twice
  resources/js/app-layout.js
  resources/views/layouts/navbar.blade.php
Labels: codeball:needs-review

#4708 FOUR-8303-Fix issues with RC upgrades is_template column
  database/migrations/2023_04_26_164247_add_is_template_column_to_specific_version_tables.php
Labels: codeball:needs-careful-review

#4702 Fix category assignment on screen import
  ProcessMaker/Jobs/ImportProcess.php
Labels: codeball:needs-careful-review

#4707 The Add button in LDAP Attributes looks distorted
  resources/js/admin/settings/components/SettingObject.vue
Labels: codeball:needs-careful-review

#4712 The "By user ID" assignment rule in sub-processes does not display the "Variable Name" field.
  resources/js/processes/modeler/initialLoad.js
Labels: codeball:needs-careful-review

#4713 500 Error in Public files
  ProcessMaker/Http/Controllers/Api/FileController.php
Labels: codeball:needs-careful-review

#4719 Increase process template page limit
  resources/js/components/templates/TemplateSearch.vue
Labels: codeball:approved

#4721 Improve error message for process exporting and saving as a template
  ProcessMaker/Exception/ExportModelNotFoundException.php
  ProcessMaker/Http/Controllers/Api/ExportController.php
  ProcessMaker/Templates/ProcessTemplate.php
  resources/js/components/templates/CreateTemplateModal.vue
  resources/js/processes/export/DataProvider.js
  resources/js/processes/export/state.js
Labels: codeball:needs-careful-review

#4717 Bugfix FOUR-7330-a
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  resources/js/processes/modeler/components/inspector/ConfigEditor.vue
  resources/sass/app.scss
Labels: codeball:needs-review

#4723 FOUR-8145 | Template is Not Created With the Correct Time Zone
  ProcessMaker/Models/Template.php
Labels: codeball:approved

#4709 Category tab is not displayed in Designer > Data connectors
  resources/views/components/categorized_resource.blade.php
Labels: codeball:needs-careful-review

#4726 Users/Groups assignment is lost with self services configuration
  resources/js/components/SelectUserGroup.vue
Labels: codeball:needs-careful-review

#4718 FOUR-8318 | Add ‘Save as Template’ Button to Modeler
  resources/js/components/templates/CreateTemplateModal.vue
  resources/js/processes/modeler/components/ModelerApp.vue
Labels: codeball:needs-careful-review

#4727 4.6.0-RC6
  composer.json
  composer.lock
  package-lock.json
  package.json
Labels: codeball:needs-careful-review
