Repository ProcessMaker/processmaker, pull requests merged in 2023-02, with the labels that each got.

#4608 FOUR-7269: Remove active user notifications query from view
  resources/views/layouts/layout.blade.php
Labels: codeball:needs-review

#4614 FOUR-7299: Import/Export UI Updates
  resources/js/components/shared/Container.vue
  resources/js/components/shared/DataCard.vue
  resources/js/components/shared/SidebarButton.vue
  resources/js/components/shared/SidebarNav.vue
  resources/js/processes/export/components/CustomExportView.vue
  resources/js/processes/export/components/process-elements/ScriptsView.vue
  resources/sass/app.scss
Labels: codeball:needs-careful-review

#4612 Import/Export FOUR-7313: Handle backwards compatibility for older process versions
  ProcessMaker/Http/Controllers/Api/ImportController.php
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  resources/js/processes/export/DataProvider.js
  resources/js/processes/import/components/ImportManagerView.vue
  resources/js/processes/import/components/OldProcessImporter.vue
  tests/Feature/ImportExport/Api/ExportImportTest.php
  tests/Feature/ImportExport/fixtures/old-process-payload-41.json
Labels: codeball:needs-careful-review

#4616 Update MySql requirement to 8.0
  README.md
Labels: codeball:approved

#4617 Fix dropdowns in request list
  resources/js/components/AdvancedSearch.vue
Labels: codeball:approved

#4618 Set processmaker_intended cookie to sameSite=none
  ProcessMaker/Http/Controllers/Auth/LoginController.php
Labels: codeball:approved

#4624 Prevent clearing values on radio buttons
  resources/js/admin/settings/components/SettingsListing.vue
Labels: codeball:needs-review

#4623 Add section indexed on page about
  resources/views/about/index.blade.php
Labels: codeball:approved

#4606 Make an improvement for updating notifications when you have many records.
  ProcessMaker/Http/Controllers/Api/NotificationController.php
  ProcessMaker/Http/Controllers/TaskController.php
  ProcessMaker/Jobs/MarkNotificationAsRead.php
  ProcessMaker/Models/Notification.php
  ProcessMaker/Notifications/ActivityActivatedNotification.php
  ProcessMaker/Notifications/ActivityCompletedNotification.php
  ProcessMaker/Notifications/NotificationChannel.php
  ProcessMaker/Notifications/ProcessCanceledNotification.php
  ProcessMaker/Notifications/ProcessCompletedNotification.php
  ProcessMaker/Notifications/ProcessCreatedNotification.php
  ProcessMaker/Notifications/TaskOverdueNotification.php
  ProcessMaker/Notifications/TaskReassignmentNotification.php
  database/factories/ProcessMaker/Models/NotificationFactory.php
  database/migrations/2023_01_20_184154_create_notification_virtual_column_url.php
  tests/Feature/NotificationControlsTest.php
Labels: codeball:needs-careful-review

#4597 Including user permissions data regarding the request - FOUR-7187
  ProcessMaker/Http/Resources/Task.php
Labels: codeball:needs-review

#4596 FOUR-6704: Updated Task API with processRequestParent()
  ProcessMaker/Http/Resources/Task.php
  tests/Feature/Api/TasksTest.php
Labels: codeball:needs-review

#4486 Bugfix/FOUR-5826:Rich Text Area doesn't load HTML text the first time, data connector not working properly with text area
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/Api/TaskController.php
  ProcessMaker/Repositories/ExecutionInstanceRepository.php
  ProcessMaker/SanitizeHelper.php
  tests/Feature/Api/SanitizeHelperTest.php
Labels: codeball:needs-careful-review

#4621 FOUR-7264 - Default timezone for new users
  ProcessMaker/Http/Controllers/Api/UserController.php
  ProcessMaker/Models/User.php
  ProcessMaker/Observers/UserObserver.php
  tests/Feature/Api/UsersTest.php
Labels: codeball:needs-careful-review

#4602 FOUR-470 - Translations: &#039; instead of single quote
  resources/js/processes/categories/components/CategoriesListing.vue
  resources/js/processes/screens/components/modal/modal-screen-add.vue
  resources/views/admin/groups/index.blade.php
  resources/views/admin/users/edit.blade.php
  resources/views/processes/edit.blade.php
  resources/views/processes/environment-variables/edit.blade.php
  resources/views/processes/export.blade.php
  resources/views/processes/import.blade.php
  resources/views/processes/screens/edit.blade.php
  resources/views/processes/screens/export.blade.php
  resources/views/processes/screens/import.blade.php
  resources/views/processes/signals/index.blade.php
  resources/views/requests/show.blade.php
  resources/views/tasks/edit.blade.php
Labels: codeball:approved

#4440 Bugfix/FOUR-6296: Files are not recovered in sub-process
  ProcessMaker/Console/Commands/MissingFilesUploadId.php
  ProcessMaker/Events/Logout.php
  ProcessMaker/Events/SessionStarted.php
  ProcessMaker/Helpers/PmHash.php
  ProcessMaker/Helpers/StringHelper.php
  ProcessMaker/Http/Controllers/Api/NotificationController.php
  ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php
  ProcessMaker/Http/Controllers/RequestController.php
  ProcessMaker/Http/Middleware/EncryptCookies.php
  ProcessMaker/Http/Resources/Task.php
  ProcessMaker/Jobs/CopyRequestFiles.php
  ProcessMaker/Jobs/MarkNotificationAsRead.php
  ProcessMaker/Jobs/RunScriptTask.php
  ProcessMaker/Media.php
  ProcessMaker/Models/CallActivity.php
  ProcessMaker/Models/Media.php
  ProcessMaker/Models/ProcessRequest.php
  ProcessMaker/Models/ProcessRequestToken.php
  ProcessMaker/Models/RequestDevice.php
  ProcessMaker/Models/SignalData.php
  ProcessMaker/Notifications/ResetPassword.php
  ProcessMaker/Providers/ProcessMakerServiceProvider.php
  ProcessMaker/Repositories/ExecutionInstanceRepository.php
  ProcessMaker/RetryProcessRequest.php
  ProcessMaker/Traits/MakeHttpRequests.php
Labels: codeball:needs-careful-review
