Repository ProcessMaker/processmaker, pull requests merged in 2023-03, with the labels that each got.

#4632 FOUR-7264 - Default timezone for new users - a
  ProcessMaker/Http/Controllers/Api/UserController.php
  ProcessMaker/Observers/UserObserver.php
  tests/Feature/Api/UsersTest.php
Labels: codeball:needs-review

#4638 FOUR-3375 The file preview control shows the same file in all multi-instance tasks
  ProcessMaker/Http/Resources/Task.php
  ProcessMaker/Models/ProcessRequestToken.php
  resources/views/tasks/edit.blade.php
Labels: codeball:approved

#4627 FOUR-7331 - Autosave Process
  .eslintrc.js
  .gitignore
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/Process/ModelerController.php
  ProcessMaker/Models/Process.php
  ProcessMaker/Models/ProcessVersion.php
  ProcessMaker/Models/ScreenVersion.php
  ProcessMaker/Models/ScriptExecutorVersion.php
  ProcessMaker/Models/ScriptVersion.php
  ProcessMaker/Traits/HasVersioning.php
  database/migrations/2023_02_27_130520_add_draft_column_to_versions_tables.php
  resources/js/processes/modeler/components/ModelerApp.vue
  resources/views/processes/modeler/index.blade.php
  routes/api.php
  tests/Feature/Api/ProcessTest.php
  tests/Feature/Api/UsersTest.php
Labels: codeball:needs-careful-review

#4630 Add Select list field to settings table
  resources/js/admin/settings/components/SettingChoice.vue
  resources/js/admin/settings/components/SettingSelect.vue
  resources/js/admin/settings/components/SettingsListing.vue
Labels: codeball:needs-review

#4648 Bugfix/FOUR-7693: Error when exporting a process with the Custom option in branch develop
  resources/js/processes/export/components/MainAssetView.vue
Labels: codeball:approved

#4640 Bugfix/FOUR-7636: Fix the regex that detects PMQL
  resources/js/modules/isPMQL.js
Labels: codeball:needs-review

#4605 FOUR-7198: Dynamic Assignment Rules
  ProcessMaker/Models/Process.php
  ProcessMaker/Models/ProcessRequestToken.php
  ProcessMaker/Repositories/TokenRepository.php
  resources/js/processes/modeler/components/inspector/TaskAssignment.vue
  resources/lang/en.json
  resources/views/processes/modeler/index.blade.php
  tests/Feature/Api/TaskAssignmentByVariableTest.php
  tests/Feature/Api/processes/AssignmentByProcessVariable.bpmn
Labels: codeball:needs-careful-review

#4647 [FOUR-7696] 4.4.1 Merge
  ProcessMaker/Http/Controllers/Api/UserController.php
  ProcessMaker/Http/Resources/Task.php
  ProcessMaker/Models/ProcessRequestToken.php
  ProcessMaker/Observers/UserObserver.php
  package-lock.json
  package.json
  resources/views/tasks/edit.blade.php
  tests/Feature/Api/UsersTest.php
Labels: codeball:needs-careful-review

#4641 Process Templates: Add Import/Export functionality
  ProcessMaker/Http/Controllers/Api/ExportController.php
  ProcessMaker/Http/Controllers/Api/ImportController.php
  ProcessMaker/Http/Controllers/Api/TemplateController.php
  ProcessMaker/Http/Controllers/TemplateController.php
  ProcessMaker/ImportExport/Exporters/ExporterBase.php
  ProcessMaker/ImportExport/Exporters/TemplateExporter.php
  ProcessMaker/Models/ProcessTemplateCategory.php
  ProcessMaker/Models/ProcessTemplates.php
  ProcessMaker/Models/Template.php
  ProcessMaker/Models/TemplateCategory.php
  ProcessMaker/Templates/ProcessTemplate.php
  database/factories/ProcessMaker/Models/ProcessTemplateCategoryFactory.php
  database/factories/ProcessMaker/Models/ProcessTemplatesFactory.php
  database/migrations/2023_03_06_173333_create_process_template_categories_table.php
  database/migrations/2023_03_09_023511_create_process_templates_table.php
  resources/js/processes/export/components/MainAssetView.vue
  resources/js/processes/import/components/ImportManagerView.vue
  resources/js/processes/import/components/ImportProcessModal.vue
  resources/js/templates/components/ProcessTemplatesListing.vue
  resources/js/templates/import/components/TemplateDetailConfigs.vue
  resources/js/templates/import/index.js
  resources/js/templates/index.js
  resources/views/templates/import.blade.php
  resources/views/templates/list.blade.php
  routes/web.php
  tests/Feature/Templates/Api/ProcessTemplateTest.php
  webpack.mix.js
Labels: codeball:needs-careful-review

#4654 Bugfix/FOUR-7718: The save process frame is distorted, compared to the previous version
  resources/js/components/shared/Modal.vue
Labels: codeball:needs-review

#4653 Bugfix/FOUR-7715: The category is not shown in the custom import template of a process,
  ProcessMaker/ImportExport/Dependent.php
  resources/js/processes/export/DataProvider.js
Labels: codeball:needs-review

#4650 Bugfix/FOUR-7699: Linked assets observations (last modified undefined, non existing user N/A hyperlinked)
  resources/js/components/shared/AssetTreeModal.vue
Labels: codeball:approved

#4655 FOUR-7198: Dynamic Assignment Rules (Fixes)
  ProcessMaker/Models/Process.php
  ProcessMaker/Repositories/TokenRepository.php
Labels: codeball:needs-review

#4658 The task should not be Selfservice to be able to reassign.
  resources/views/tasks/edit.blade.php
Labels: codeball:needs-review

#4660 Cannot route a case to a self-service task
  ProcessMaker/Repositories/TokenRepository.php
Labels: codeball:needs-review

#4656 Process Templates: Create a Process from a Template
  ProcessMaker/Http/Controllers/Api/ExportController.php
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/Api/TemplateController.php
  ProcessMaker/Http/Controllers/TemplateController.php
  ProcessMaker/ImportExport/Exporters/ExporterBase.php
  ProcessMaker/Models/ProcessTemplates.php
  ProcessMaker/Models/Template.php
  ProcessMaker/Templates/Fixtures/process-employee-onboarding-template.json
  ProcessMaker/Templates/Fixtures/process-employee-onboarding-template.svg
  ProcessMaker/Templates/ProcessTemplate.php
  ProcessMaker/Templates/TemplateInterface.php
  ProcessMaker/Traits/HideSystemResources.php
  composer.json
  database/migrations/2023_03_09_023511_create_process_templates_table.php
  database/seeders/DatabaseSeeder.php
  database/seeders/ProcessTemplatesSeeder.php
  resources/js/components/templates/CreateTemplateModal.vue
  resources/js/components/templates/SelectTemplateModal.vue
  resources/js/components/templates/TemplateDetails.vue
  resources/js/components/templates/TemplateSearch.vue
  resources/js/components/templates/TemplateSelectCard.vue
  resources/js/processes/components/CreateProcessModal.vue
  resources/js/processes/modeler/components/ModelerApp.vue
  resources/js/templates/categories/components/CategorySelect.vue
  resources/js/templates/categories/index.js
  resources/js/templates/components/ProcessTemplatesListing.vue
  resources/js/templates/configure.js
  resources/js/templates/index.js
  resources/views/processes/list.blade.php
  resources/views/templates/configure.blade.php
  routes/api.php
  tests/Feature/Templates/Api/ProcessTemplateTest.php
Labels: codeball:needs-careful-review
