Repository ProcessMaker/processmaker, pull requests merged in 2024-07, with the labels that each got.

#7128 FOUR-17216: Update Import/Export Alert
  ProcessMaker/ImportExport/Exporters/ProcessExporter.php
  resources/js/processes/import/components/ImportManagerView.vue
  resources/js/processes/import/components/ImportProcessModal.vue
  resources/js/processes/import/components/WarningMessage.vue
  resources/lang/de.json
  resources/lang/en.json
  resources/lang/es.json
  resources/lang/fr.json
Labels: conflicts_solved

#7137 FOUR-17270: RPA type tasks do not have target information in overview
  resources/js/processes/modeler/components/ProcessMap.vue
Labels: failing

#7104 FOUR-17021 `Start This process` button are not displaying the correct UI
  resources/js/processes-catalogue/components/ProcessHeaderStart.vue
  resources/js/processes-catalogue/components/optionsMenu/ButtonsStart.vue
  resources/lang/de.json
  resources/lang/en.json
  resources/lang/es.json
  resources/lang/fr.json
Labels: conflicts

#7131 FOUR-16892 launchpad > collapsable side bar is not interactive
  resources/js/processes-catalogue/components/ProcessesCatalogue.vue
Labels: conflicts
