Repository ProcessMaker/processmaker, pull requests merged in 2024-01, with the labels that each got.

#5900 FOUR-12960:The list of processes is not reset when you select the same tab
  resources/js/processes-catalogue/components/ProcessesCatalogue.vue
Labels: conflicts

#5958 FOUR-13098 | User With Permissions to Create Processes Does Not Have the Processes Option in Sidebar Menu
  ProcessMaker/Http/Controllers/Auth/LoginController.php
Labels: conflicts

#5977 QA observation bugfix/FOUR-12799: Select lists are different controls in the launch pad modal
  resources/js/components/shared/IconDropdown.vue
Labels: hold

#5961 FOUR-13162: The categories are not listed alphabetically in Launch Pad
  ProcessMaker/Http/Controllers/Api/ProcessCategoryController.php
  resources/js/processes-catalogue/components/ProcessesCatalogue.vue
  resources/js/processes-catalogue/components/menuCatologue.vue
Labels: conflicts

#5982 FOUR-12974:There is not loading spinner in the search for processes
  resources/js/processes-catalogue/components/CardProcess.vue
  resources/js/processes-catalogue/components/menuCatologue.vue
Labels: conflicts

#5967 FOUR-13025: Message when there are no processes available in a category
  resources/js/processes-catalogue/components/CardProcess.vue
  resources/js/processes-catalogue/components/CatalogueEmpty.vue
  resources/js/processes-catalogue/components/ProcessesCatalogue.vue
  resources/js/processes-catalogue/components/utils/EmptySearch.vue
  resources/js/processes-catalogue/components/utils/SearchCards.vue
Labels: hold, conflicts

#5968 QA Observation Bugfix/FOUR-13079: The column layout of the request tables is different from that of Figma.
  resources/js/processes-catalogue/components/RequestTab.vue
  resources/js/processes-catalogue/components/TaskTab.vue
Labels: hold
