Repository ProcessMaker/processmaker, pull requests merged in 2024-12, with the labels that each got.

#7776 FOUR-21117: Platform labels are not showing in the list of strings for translation.
  resources/js/processes/designer/Assets.vue
  resources/lang/en.json
Labels: priority

#7781 observation/FOUR-21138 devLink > Server error message is displayed when a Collection is downloaded
  ProcessMaker/Enums/ExporterMap.php
Labels: priority

#7778 FOUR-21130: The users needs to have per default the permissions "View My Request"
  database/seeders/PermissionSeeder.php
  tests/Feature/Api/PermissionsTest.php
  upgrades/2024_11_28_154502_assign_user_permission_view_my_request.php
Labels: priority

#7780 FOUR-21104 : Mobile > Tabs do not have the correct style
  resources/views/layouts/navbarMobile.blade.php
Labels: priority

#7763 FOUR-20281: [SPRING] Remove fades on tab switching
  ProcessMaker/Console/Commands/SyncTranslations.php
  ProcessMaker/Enums/ExporterMap.php
  ProcessMaker/Filters/BaseFilter.php
  ProcessMaker/Http/Controllers/Api/SecurityLogController.php
  ProcessMaker/Jobs/RunServiceTask.php
  ProcessMaker/Traits/TaskControllerIndexMethods.php
  composer.json
  composer.lock
  database/seeders/PermissionSeeder.php
  database/seeders/RenameRequestsToCasesPermissionSeeder.php
  package-lock.json
  package.json
  resources/js/processes/designer/Assets.vue
  resources/jscomposition/cases/casesMain/utils/counters.js
  resources/lang/de.json
  resources/lang/en.json
  resources/lang/es.json
  resources/lang/fr.json
  resources/views/admin/users/index.blade.php
  resources/views/components/categorized_resource.blade.php
  resources/views/layouts/navbarMobile.blade.php
  resources/views/processes/edit.blade.php
  resources/views/processes/screens/edit.blade.php
  resources/views/processes/scripts/edit.blade.php
  resources/views/processes/signals/edit.blade.php
  resources/views/requests/index.blade.php
  resources/views/requests/show.blade.php
  resources/views/requests/showMobile.blade.php
  resources/views/tasks/edit.blade.php
  resources/views/tasks/index.blade.php
  resources/views/templates/configure.blade.php
  tests/Feature/Api/PermissionsTest.php
  tests/Feature/Api/SecurityLogControllerTest.php
  tests/TestCase.php
  upgrades/2024_11_19_161132_create_permission_view_all_cases_all_requests.php
  upgrades/2024_11_28_154502_assign_user_permission_view_my_request.php
  webpack-login.mix.js
Labels: spring-2025

#7819 FOUR-20588: Define an column in user to save this kind of configurations
  ProcessMaker/Http/Controllers/Api/UserConfigurationController.php
  ProcessMaker/Models/UserConfiguration.php
  database/migrations/2024_12_11_161527_add_ui_filters_column_in_user_configuration.php
  routes/api.php
  tests/Feature/Api/UserConfigurationTest.php
Labels: spring-2025

#7777 FOUR-21125 When assigning two categories to screens/scripts/decision tables the category disappears
  resources/js/components/shared/FilterTableBodyMixin.js
  resources/js/processes/screens/components/ScreenListing.vue
  resources/js/processes/scripts/components/ScriptListing.vue
Labels: 4.12.1

#7800 Task/FOUR-21198: Create command to revoke specified API tokens
  ProcessMaker/Console/Commands/RevokeOauthAccessTokens.php
Labels: 4.12.1

#7797 FOUR-21166 Reassigment capability adjustments
  resources/views/processes/edit.blade.php
  routes/api.php
  tests/Feature/Api/UsersTest.php
Labels: PerformanceReviewRequired
