Repository ProcessMaker/processmaker, pull requests merged in 2024-08, with the labels that each got.

#7138 FOUR-17235: POC Implement the icons like a font
  .gitignore
  README.md
  devhub/pm-font/svg/brush-icon.svg
  devhub/pm-font/svgtofont.js
  devhub/pm-font/template.ejs
  package.json
  resources/fonts/pm-font/index.html
  resources/fonts/pm-font/processmaker-font.css
  resources/fonts/pm-font/processmaker-font.eot
  resources/fonts/pm-font/processmaker-font.less
  resources/fonts/pm-font/processmaker-font.module.less
  resources/fonts/pm-font/processmaker-font.scss
  resources/fonts/pm-font/processmaker-font.styl
  resources/fonts/pm-font/processmaker-font.svg
  resources/fonts/pm-font/processmaker-font.symbol.svg
  resources/fonts/pm-font/processmaker-font.ttf
  resources/fonts/pm-font/processmaker-font.woff
  resources/fonts/pm-font/processmaker-font.woff2
  resources/sass/app.scss
Labels: hold

#7268 observation/FOUR-18176 Make Tasks the first tab and show it opened in the Launchpad
  resources/js/processes-catalogue/components/ProcessTab.vue
Labels: 4.11.1

#7272 FOUR-18163 the element destination configuration with custom dashboard is not imported
  ProcessMaker/ImportExport/Exporters/ProcessExporter.php
Labels: 4.11.2
