Repository ProcessMaker/processmaker, pull requests merged in 2024-09, with the labels that each got.

#7315 FOUR-16700: XSS via PDF File Upload (for 4.10.2)
  ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php
  resources/lang/en.json
Labels: 4.10.2+patch-ellucian

#7265 Use the first admin user if user_id is not set (next)
  ProcessMaker/ImportExport/Exporters/ProcessExporter.php
Labels: 4.11.2

#7261 Performance Enhancements for Projects Package (rebase)
  ProcessMaker/Http/Controllers/Api/PermissionController.php
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/Api/ScreenController.php
  ProcessMaker/Http/Controllers/Api/ScriptController.php
  ProcessMaker/Http/Controllers/Auth/LoginController.php
  ProcessMaker/Http/Kernel.php
  ProcessMaker/Http/Middleware/CustomAuthorize.php
  ProcessMaker/Http/Middleware/GenerateMenus.php
  ProcessMaker/Models/Permission.php
  ProcessMaker/Models/Process.php
  ProcessMaker/Models/Screen.php
  ProcessMaker/Models/Script.php
  ProcessMaker/Models/User.php
  ProcessMaker/Providers/AuthServiceProvider.php
  ProcessMaker/Traits/HasAuthorization.php
  ProcessMaker/Traits/ProjectAssetTrait.php
  tests/Feature/Shared/RequestHelper.php
  tests/Model/UserTest.php
Labels: 4.11.2

#7286 FOUR-17398 Date filter is shown in ISO 8601 format and in UTC confusi…
  resources/js/common/advancedFilterStatusMixin.js
  resources/js/components/PMColumnFilterPopover/PMColumnFilterOpDatetime.vue
  resources/js/components/PMDatetimePicker.vue
Labels: 4.11.2

#7294 FOUR-18876 Fix Wrong german label for Elementziel
  resources/lang/de.json
Labels: 4.11.2

#7300 FOUR-17348 Users endpoint being called in Requests/Cases and Tasks tr…
  resources/js/common/PMColumnFilterPopoverCommonMixin.js
  resources/js/requests/components/RequestsListing.vue
  resources/js/tasks/components/TasksList.vue
Labels: 4.11.2

#7289 feature/FOUR-17157: Import/Export: ABE screens are not imported in a process
  ProcessMaker/ImportExport/DependentType.php
  ProcessMaker/ImportExport/Exporters/ProcessExporter.php
  tests/Feature/ImportExport/Exporters/ProcessExporterTest.php
  tests/Feature/ImportExport/fixtures/process-with-abe-screen.bpmn.xml
  tests/Feature/ImportExport/fixtures/process-without-abe-properties.bpmn.xml
  tests/Feature/ImportExport/fixtures/process-without-abe-screen.bpmn.xml
Labels: 4.11.2

#7266 Query too slow, when using request endpoint
  ProcessMaker/Traits/ForUserScope.php
Labels: 4.11.2

#7309 FOUR-18004 Add a env variable SWAGGER_AUTH_REQUIRED to enable the auth for swagger routes
  config/l5-swagger.php
Labels: 4.11.2

#7308 FOUR-18090: Fix conflict during data source script postImport
  ProcessMaker/ImportExport/Importer.php
Labels: 4.11.2

#7312 FOUR-16700: XSS via PDF File Upload
  ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php
  resources/lang/en.json
Labels: 4.11.2

#7323 FOUR-18920 Fix environment variable encoding for nayra executor
  ProcessMaker/ScriptRunners/Base.php
Labels: 4.11.2

#7332 FOUR-18974: The user assigned to the task with self service enabled is not redirected to the self service task
  ProcessMaker/Http/Controllers/Api/V1_1/TaskController.php
  ProcessMaker/Models/ProcessRequestToken.php
Labels: 4.11.2

#7328 FOUR-18984 Parallel Task is not redirected according element destination configuration once completed
  ProcessMaker/Listeners/HandleActivityCompletedRedirect.php
Labels: 4.11.2

#7344 FOUR-18897
  resources/js/bootstrap.js
  resources/views/layouts/ai-qr-mobile.blade.php
  resources/views/layouts/layout.blade.php
  resources/views/layouts/minimal.blade.php
  resources/views/layouts/preview.blade.php
  resources/views/layouts/process-map.blade.php
  resources/views/tasks/preview.blade.php
Labels: 4.11.2

#7281 FOUR-17278 Remove temporal files from failing script tasks
  ProcessMaker/Models/ScriptDockerBindingFilesTrait.php
  upgrades/2024_08_26_220829_remove_old_script_files.php
Labels: 4.11.2, migrations

#7348 bugfix/FOUR-17453-4.11 Issue with Reassigning Tasks Without Claiming First in Self Service
  resources/views/tasks/edit.blade.php
Labels: 4.11.2

#7297 FOUR-17408: [4.11.2] Slideshow Improvements
  .gitignore
  ProcessMaker/Jobs/CompileSass.php
  README.md
  devhub/pm-font/svg/bpmn-action-by-email.svg
  devhub/pm-font/svg/bpmn-data-connector.svg
  devhub/pm-font/svg/bpmn-data-object.svg
  devhub/pm-font/svg/bpmn-data-store.svg
  devhub/pm-font/svg/bpmn-docusign.svg
  devhub/pm-font/svg/bpmn-end-event.svg
  devhub/pm-font/svg/bpmn-flowgenie.svg
  devhub/pm-font/svg/bpmn-gateway.svg
  devhub/pm-font/svg/bpmn-generic-gateway.svg
  devhub/pm-font/svg/bpmn-idp.svg
  devhub/pm-font/svg/bpmn-intermediate-event.svg
  devhub/pm-font/svg/bpmn-pool.svg
  devhub/pm-font/svg/bpmn-send-email.svg
  devhub/pm-font/svg/bpmn-start-event.svg
  devhub/pm-font/svg/bpmn-task.svg
  devhub/pm-font/svg/bpmn-text-annotation.svg
  devhub/pm-font/svg/brush-icon.svg
  devhub/pm-font/svg/close.svg
  devhub/pm-font/svg/copy.svg
  devhub/pm-font/svg/desktop.svg
  devhub/pm-font/svg/eye.svg
  devhub/pm-font/svg/fullscreen.svg
  devhub/pm-font/svg/github.svg
  devhub/pm-font/svg/map.svg
  devhub/pm-font/svg/mobile.svg
  devhub/pm-font/svg/pdf.svg
  devhub/pm-font/svg/plus.svg
  devhub/pm-font/svg/slack-notification.svg
  devhub/pm-font/svg/slack.svg
  devhub/pm-font/svg/slideshow.svg
  devhub/pm-font/svg/table.svg
  devhub/pm-font/svgtofont.js
  devhub/pm-font/template.ejs
  package.json
  resources/fonts/pm-font/fp.eot
  resources/fonts/pm-font/fp.svg
  resources/fonts/pm-font/fp.ttf
  resources/fonts/pm-font/fp.woff
  resources/fonts/pm-font/fp.woff2
  resources/fonts/pm-font/index.html
  resources/fonts/pm-font/processmaker-font.css
  resources/fonts/pm-font/processmaker-font.eot
  resources/fonts/pm-font/processmaker-font.less
  resources/fonts/pm-font/processmaker-font.module.less
  resources/fonts/pm-font/processmaker-font.scss
  resources/fonts/pm-font/processmaker-font.styl
  resources/fonts/pm-font/processmaker-font.svg
  resources/fonts/pm-font/processmaker-font.symbol.svg
  resources/fonts/pm-font/processmaker-font.ttf
  resources/fonts/pm-font/processmaker-font.woff
  resources/fonts/pm-font/processmaker-font.woff2
  resources/fonts/pm-font/symbol.html
  resources/fonts/pm-font/unicode.html
  resources/img/processmaker.png
  resources/sass/app.scss
Labels: 4.11.2

#7357 FOUR-18603 cases started table and view the list of all cases in the system ep
  ProcessMaker/Http/Controllers/Api/V1_1/CaseController.php
  ProcessMaker/Http/Requests/GetAllCasesRequest.php
  ProcessMaker/Http/Resources/V1_1/CaseResource.php
  ProcessMaker/Models/CaseStarted.php
  ProcessMaker/Rules/SortBy.php
  database/factories/CaseStartedFactory.php
  database/migrations/2024_09_09_181717_create_cases_started_table.php
  routes/v1_1/api.php
Labels: migrations

#7364 Add missing user attributes
  ProcessMaker/Http/Resources/V1_1/TaskResource.php
Labels: 4.11.2

#7367 FOUR-19102 Fix Redirect when the process ends before load the request
  ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
  routes/api.php
Labels: 4.11.2

#7366 FOUR-19115 Fix when the Redirect must be triggered
  ProcessMaker/Http/Controllers/Api/TaskController.php
  ProcessMaker/Jobs/BpmnAction.php
Labels: 4.11.2

#7356 FOUR-19101 Filter Tags in Tasks and Cases Pages are displaying other …
  resources/js/common/advancedFilterStatusMixin.js
Labels: 4.11.2

#7382 FOUR-19210: Error when Importing Guided Template
  ProcessMaker/Models/ProcessRequestToken.php
Labels: 4.11.3

#7417 FOUR-19373: Incorrect validation - Error uploading PDF file: Dangerous content of PDF file
  ProcessMaker/Http/Controllers/Api/ProcessRequestFileController.php
Labels: 4.11.4

#7427 FOUR-19110: [40531] changes on screen are not reflected in ongoing cases
  resources/views/tasks/edit.blade.php
Labels: 4.11.4

#7432 FOUR-19390 Fix call to missing method
  ProcessMaker/Models/Process.php
  tests/unit/ProcessMaker/Models/ProcessTest.php
Labels: 4.11.4

#7428 Allow admin users to reassign any user task
  ProcessMaker/Models/ProcessRequestToken.php
  ProcessMaker/Policies/ProcessRequestTokenPolicy.php
  database/factories/ProcessMaker/Models/UserFactory.php
  tests/Feature/Api/ProcessRequestTokenPolicyTest.php
Labels: 4.11.4

#7430 FOUR-19402 Fix self_service_groups variable types
  ProcessMaker/Repositories/TokenRepository.php
Labels: 4.11.4
