Repository ProcessMaker/processmaker, pull requests merged in 2024-10, with the labels that each got.

#7443 No data is shown in parallel screens
  ProcessMaker/Http/Resources/V1_1/TaskResource.php
  tests/Feature/Api/V1_1/TaskControllerTest.php
Labels: 4.11.5

#7461 The Block duplicate session in IP Restriction option only works the first time
  ProcessMaker/Http/Controllers/Auth/LoginController.php
Labels: 4.11.5

#7495 Feature/FOUR-18116: STORY Add Collection View Control in Display Screens
  resources/js/processes/screen-builder/typeDisplay.js
  resources/js/processes/screen-builder/typeForm.js
Labels: 4.12.0

#7470 FOUR-19482 | Placeholder Text for All Templates Search Is Not Correct in LaunchPad
  resources/js/processes-catalogue/components/CardProcess.vue
  resources/js/processes-catalogue/components/menuCatologue.vue
  resources/js/processes-catalogue/components/utils/SearchCards.vue
Labels: 4.11.6

#7479 FOUR-19276: Add parameter in the login
  ProcessMaker/Http/Controllers/Auth/LoginController.php
Labels: 4.11.6

#7460 FOUR-19272: CSS style is not rendering in Summary section
  resources/views/requests/show.blade.php
Labels: 4.11.6

#7444 FOUR-17680: [39200] AutoSave feature does not save correctly for New Line
  ProcessMaker/Http/Controllers/Api/TaskDraftController.php
Labels: 4.11.6

#7436 FOUR-17328 Patch generated SDK code to fix error
  ProcessMaker/BuildSdk.php
Labels: 4.11.6

#7531 feature/FOUR-19522 file manager option on the Case Detail
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/Api/ProcessRequestController.php
  ProcessMaker/Http/Controllers/Api/TaskDraftController.php
  ProcessMaker/Http/Controllers/Auth/LoginController.php
  ProcessMaker/Managers/ScreenCompiledManager.php
  ProcessMaker/Models/ProcessRequestToken.php
  ProcessMaker/ProcessTranslations/MenuTranslation.php
  ProcessMaker/ProcessTranslations/TranslationManager.php
  ProcessMaker/Providers/ProcessMakerServiceProvider.php
  ProcessMaker/Repositories/CaseApiRepository.php
  ProcessMaker/Repositories/CaseUtils.php
  ProcessMaker/Repositories/ExecutionInstanceRepository.php
  ProcessMaker/SanitizeHelper.php
  ProcessMaker/ScriptRunners/Base.php
  ProcessMaker/Traits/TaskControllerIndexMethods.php
  devhub/pm-font/svg/unlink.svg
  resources/fonts/pm-font/index.html
  resources/fonts/pm-font/processmaker-font.css
  resources/fonts/pm-font/processmaker-font.eot
  resources/fonts/pm-font/processmaker-font.less
  resources/fonts/pm-font/processmaker-font.module.less
  resources/fonts/pm-font/processmaker-font.scss
  resources/fonts/pm-font/processmaker-font.styl
  resources/fonts/pm-font/processmaker-font.svg
  resources/fonts/pm-font/processmaker-font.symbol.svg
  resources/fonts/pm-font/processmaker-font.ttf
  resources/fonts/pm-font/processmaker-font.woff
  resources/fonts/pm-font/processmaker-font.woff2
  resources/fonts/pm-font/symbol.html
  resources/fonts/pm-font/unicode.html
  resources/jscomposition/cases/casesDetail/components/CaseDetail.vue
  resources/jscomposition/cases/casesDetail/components/TabFiles.vue
  resources/jscomposition/cases/casesDetail/components/Tabs.vue
  resources/views/cases/edit.blade.php
  routes/api.php
  tests/Feature/Api/V1_1/CaseUtilsTest.php
  tests/Feature/Cases/CaseParticipatedTest.php
  tests/Feature/Screens/ScreenCompiledManagerTest.php
Labels: 4.12.0
