Repository ProcessMaker/processmaker, pull requests merged in 2025-06, with the labels that each got.

#8268 Axios timeour after 60000ms in Flow Genie
  config/ai.php
  resources/views/layouts/layout.blade.php
Labels: PO Backlog Bug, Beta2, FutureRelease

#8191 observation/FOUR-23820 devLink > options are not synchronized
  ProcessMaker/Http/Controllers/Api/DevLinkController.php
  ProcessMaker/Models/Bundle.php
  resources/js/admin/devlink/components/BundleSettingsModal.vue
Labels: hold, FutureRelease

#8193 FOUR-13976: Web entry link not redirecting to the screen when using default SSO SAML authentication
  ProcessMaker/Http/Controllers/Auth/LoginController.php
Labels: PO Backlog Bug, 4.15.1

#8280 FOUR-24546L The columns available in a save search can be duplicated each time we enter the save search configuration.
  ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php
Labels: Beta1, 4.15.1

#8278 FOUR-24616: The "Save and Finish" button when creating a process from a guide template is distorted
  resources/js/components/templates/WizardTemplateDetails.vue
Labels: FutureRelease

#8301 FOUR-24684 It is possible to set an invalid URL in Iframe white list.
  ProcessMaker/Http/Controllers/Api/SettingController.php
  helpers.php
  tests/Feature/Admin/SettingsControllerTest.php
Labels: Beta1, 4.15.1

#8298 FOUR-24757: UI: Update Grants according the figma
  resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButton.vue
  resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonHome.vue
  resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButton.vue
  resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButtonGroup.vue
  resources/js/processes-catalogue/components/home/TceDistributionGrants.vue
  resources/js/processes-catalogue/components/home/config/metrics.js
Labels: merge-epic

#8303 FOUR-24522: Create Index to Improve Slow Query on cases_participated
  database/migrations/2025_06_05_151344_add_index_case_number_to_cases_participated.php
Labels: PO Backlog Bug, 4.15.1

#8296 FOUR-24707: Stages - Update the Checklist design with click option
  resources/js/processes/modeler/components/inspector/StageItem.vue
  resources/js/processes/modeler/components/inspector/StageList.vue
  resources/js/processes/modeler/components/inspector/StageManager.vue
Labels: merge-epic

#8314 FOUR-23812:The variables are duplicated in Available columns in TASK and REQUEST Saved search
  ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php
Labels: Beta3, 4.15.1

#8312 FOUR-24946: The API task needs to load the 'data' only if is necesary
  ProcessMaker/Helpers/DefaultColumns.php
  ProcessMaker/Http/Controllers/TaskController.php
  resources/js/tasks/components/ListMixin.js
  resources/views/tasks/index.blade.php
  tests/unit/ProcessMaker/Helpers/DefaultColumnsTest.php
Labels: Beta1, 4.15.2

#8313 FOUR-24963: Cases and Tasks are not listed in launchpad when a saved search is added
  resources/js/processes-catalogue/components/ProcessTab.vue
Labels: Beta1, 4.15.2

#8310 FOUR-23617: When reloading the page, the completed status filter show all clear
  ProcessMaker/Traits/TaskControllerIndexMethods.php
  resources/js/tasks/components/ListMixin.js
  resources/js/tasks/components/ParticipantHomeScreen.vue
  resources/js/tasks/router.js
Labels: Beta1, 4.15.2

#8323 FOUR-24986: Code Integration with simdjson and uopz
  ProcessMaker/Providers/JsonOptimizerServiceProvider.php
  config/app.php
  docs/json-optimization.md
  tests/Fixtures/json_optimizer_test_example.json
  tests/unit/ProcessMaker/JsonOptimizerTest.php
Labels: merge-epic

#8305 FOUR-24803
  tests/Feature/Api/EnvironmentVariablesTest.php
Labels: merge-epic
