Repository ProcessMaker/processmaker, pull requests merged in 2025-08, with the labels that each got.

#8402 Bugfix/FOUR-25472: There is not translation button in login page
  resources/views/auth/newLogin.blade.php
Labels: 4.15.5

#8420 bugfix/FOUR-25670: Archived processes are listed in the Home > Inbox page
  ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php
Labels: PO Backlog Bug, version-tbd

#8400 FEATURE/FOUR-22569 Email Start Event
  ProcessMaker/Managers/TaskSchedulerManager.php
  ProcessMaker/Models/ProcessRequest.php
  ProcessMaker/Models/Setting.php
  ProcessMaker/Traits/HasComments.php
  composer.json
  resources/js/admin/settings/components/SettingChoice.vue
  resources/js/admin/settings/components/SettingsMain.vue
  resources/views/admin/settings/index.blade.php
Labels: 4.15.6

#8433 FOUR-25731:UI: There is no horizontal scroll in cases completed
  resources/jscomposition/cases/casesDetail/components/summary/DataSummary.vue
Labels: Beta3, 4.15.6

#8431 FOUR-25714:Auto scroll stop to work in process launchpad
  resources/js/processes-catalogue/components/CardProcess.vue
  resources/js/processes-catalogue/components/ProcessesCatalogue.vue
  resources/views/processes-catalogue/index.blade.php
Labels: Beta3, 4.15.6

#8427 FOUR-25717: Make customizable the message "No data available for this dynamic panel
  resources/lang/de.json
  resources/lang/en.json
  resources/lang/es.json
  resources/lang/fr.json
Labels: 4.15.6.beta3

#8449 FOUR-25820:Unable to configure SSO accounts
  resources/js/admin/settings/components/SettingsMain.vue
Labels: Beta4, 4.15.6

#8450 Multitenancy updates
  ProcessMaker/Console/Commands/TenantsCreate.php
  ProcessMaker/Multitenancy/SwitchTenant.php
  ProcessMaker/Providers/ProcessMakerServiceProvider.php
  README.md
Labels: Beta4, 4.15.6

#8451 FOUR-25816:When the TCE is disable the dashboard does not show nothing
  resources/js/processes-catalogue/components/ProcessScreen.vue
  resources/lang/en.json
Labels: Beta4, 4.15.6

#8448 FOUR-25221:UI: The summary with the cases, % needs to show with the previous UI
  resources/js/processes-catalogue/components/ProcessCollapseInfo.vue
Labels: Beta4, 4.15.6

#8447 FOUR-25729: The total cases card show only one decimal
  ProcessMaker/Models/Process.php
Labels: Beta4, 4.15.6

#8446 FOUR-25775: The Screen "Default Email Task Notification" in qa server is not updated with the last template
  ProcessMaker/Models/Screen.php
Labels: Beta4, 4.15.6

#8444 FOUR-25773:Case detail is choppy when TCE_CUSTOMIZATION_ENABLED=true
  resources/jscomposition/cases/casesDetail/components/CaseDetail.vue
  resources/jscomposition/cases/casesDetail/components/Tabs.vue
Labels: Beta4, 4.15.6

#8442 FOUR-25284:Stages are duplicated in process info
  resources/js/processes-catalogue/components/home/ProcessInfo.vue
Labels: Beta4, 4.15.6

#8463 FOUR-25965:Process name overlap the header in process launchpad
  resources/js/processes-catalogue/components/ProcessCollapseInfo.vue
Labels: Beta5, 4.15.6

#8457 Update package-pinnacle version
  composer.json
Labels: RC1, 4.15.6

#8477 FOUR-26065: Create an upgrade instead to execute the ScreenEmailSeeder
  upgrades/2025_08_26_174003_install_default_email_task_notification_screen.php
Labels: RC1, 4.15.6

#8480 Task/FOUR-26050: Hide Enable Client Credentials option from Auth
  resources/views/admin/auth-clients/index.blade.php
Labels: RC1, 4.15.6

#8453 FOUR-25905: Error in alternatives when changing the position of the stages
  ProcessMaker/Traits/HasVersioning.php
Labels: Beta1, 4.15.7

#8474 FOUR-23421 There is confusion with the stages when they are not publi…
  resources/js/processes/modeler/components/ModelerApp.vue
  resources/js/processes/modeler/components/inspector/StageManager.vue
Labels: 4.15.7
