Repository ProcessMaker/processmaker, pull requests merged in 2025-02, with the labels that each got.

#7975 FOUR-21235 | Enforce File Upload Limit When Using Chunked File Upload Component
  ProcessMaker/Http/Kernel.php
  ProcessMaker/Http/Middleware/FileSizeCheck.php
  config/app.php
  tests/unit/FileSizeCheckTest.php
Labels: 4.13.0, RC2

#7976 Bugfix/FOUR-21700: When filling any field from . web entry , we see an error in the console
  resources/views/tasks/edit.blade.php
Labels: 4.13.0, RC2

#7970 FOUR-21669: Assigned field in case detail has an empty avatar in self service
  resources/jscomposition/cases/casesDetail/config/columns.js
Labels: 4.13.0, RC2

#7969 FOUR-21657: Dynamic UI > Reset button does not work
  ProcessMaker/Http/Controllers/Api/CssOverrideController.php
Labels: 4.13.0, RC2

#7842 Remove External Integrations Setting Due to CDATA Package Deprecation
  composer.json
  database/migrations/2024_12_18_174359_remove_external_integrations_from_settings_table.php
Labels: 4.13.0, RC4

#7988 FOUR-21806: The process title slides down across the screen in the request overview
  resources/jscomposition/cases/casesDetail/components/NewOverview.vue
Labels: 4.13.0, RC4

#7980 FOUR-21704: When we open a case the following error is showing 'Screen nBuilder is not defined'
  ProcessMaker/Http/Controllers/CasesController.php
  resources/views/cases/edit.blade.php
Labels: 4.13.0, RC4

#7987 FOUR-21709 create index for table process_request_tokens
  database/migrations/2025_02_05_141451_add_index_process_request_id_status_to_process_request_tokens_table.php
Labels: 4.13.0, RC4

#7991 FOUR-21707:When we open a case the following error is showing 'ProcessesComponents is not defined'
  resources/js/next/libraries/processesCatalogueComponents.js
  resources/js/next/libraries/processesComponents.js
  resources/js/next/libraries/screensComponents.js
  resources/js/next/libraries/scriptsComponents.js
  resources/js/next/setupMain.js
Labels: 4.13.0, RC4

#7996 The filter by cases in the TASK tab does not work correctly
  resources/js/tasks/index.js
Labels: 4.13.0, RC4

#7995 Get available languages from database table
  ProcessMaker/ImportExport/Exporters/ExporterBase.php
Labels: 4.13.0, RC4

#7994 Add type cast in ScriptExecutor model
  ProcessMaker/Models/ScriptExecutor.php
  ProcessMaker/Models/ScriptExecutorVersion.php
Labels: 4.13.0, RC4

#7990 FOUR-21808 modal is not displayed the users
  resources/js/next/components/index.js
  resources/js/next/setupMain.js
Labels: 4.13.0, RC4

#8006 Enhance Error Handling and Script Executor Validation for Package Installation
  ProcessMaker/Models/Script.php
  ProcessMaker/Models/ScriptExecutor.php
Labels: 4.13.0, RC5

#8002 FOUR-21860: Requests created by signals in versions < 4.13, show an empty screen
  ProcessMaker/Traits/TaskResourceIncludes.php
Labels: 4.13.0, RC5

#7997 observation/FOUR-21805 The cancel button does not clear input from case list filters
  resources/jscomposition/system/table/filter/defaultFilter/FilterColumn.vue
Labels: 4.13.0, RC5

#8007 Run package:discover as part of the optimize command
  ProcessMaker/Console/Commands/ProcessMakerLicenseRemove.php
  ProcessMaker/Console/Commands/ProcessMakerLicenseUpdate.php
  ProcessMaker/Providers/ProcessMakerServiceProvider.php
Labels: 4.13.0, RC5

#8008 FOUR-21657: Dynamic UI > Reset button does not work
  ProcessMaker/Observers/SettingObserver.php
Labels: 4.13.0, RC6

#8012 FOUR-21893: Overview does not show the correct version of proccess
  ProcessMaker/Traits/ProcessMapTrait.php
  tests/Feature/CasesControllerTest.php
Labels: 4.13.0, RC6

#8009 FOUR-21818: Integration: Review if we can improve the time for the Overview
  ProcessMaker/Http/Controllers/CasesController.php
  resources/jscomposition/cases/casesDetail/components/CaseDetail.vue
  resources/jscomposition/cases/casesDetail/components/Tabs.vue
Labels: 4.13.0, RC6

#8033 FOUR-21966 Do not log error case log when system like processes without case are updated
  ProcessMaker/Repositories/CaseRepository.php
  tests/Feature/Cases/CaseExceptionTest.php
Labels: 4.13.1, RC1

#8005 FOUR-21712:Form Task does not enable the assigne and Due
  resources/js/processes/modeler/components/inspector/TaskNotifications.vue
Labels: merge-epic

#8034 Fix multiple generators running at once and cleanup
  ProcessMaker/BuildSdk.php
Labels: 4.13.1, RC1

#8032 Screen Interstitial does not work
  ProcessMaker/Models/ProcessRequestToken.php
  ProcessMaker/Models/Screen.php
  database/processes/screens/interstitial.json
  database/seeders/ScreenSystemSeeder.php
  tests/Feature/Processes/ExportImportScreenTest.php
  tests/Feature/Templates/Api/ProcessTemplateTest.php
Labels: 4.13.1, RC1

#8020 FOUR-21927: The signature control disappears after refresh the page
  resources/js/next/libraries/vueFormElements.js
  resources/js/next/screenBuilder.js
Labels: 4.13.1, RC1

#8030 FOUR-21958: inbox rules does not show the filter selected from the requests save search.
  resources/js/common/PMColumnFilterPopoverCommonMixin.js
Labels: 4.13.1, RC1

#8014 FOUR-21880:Overview does not show the pmblocks in Cases
  ProcessMaker/Http/Controllers/RequestController.php
  resources/jscomposition/cases/casesDetail/loader.js
  resources/views/cases/edit.blade.php
  resources/views/requests/show.blade.php
Labels: 4.13.1, RC1

#8038 FOUR-21949 there are problems running tests in the SettingCacheTest file
  tests/Feature/Cache/SettingCacheTest.php
Labels: RC2, 4.13.1

#7986 FOUR-21718: When the previous element is a element without user the text does not make sense
  ProcessMaker/Repositories/TokenRepository.php
Labels: merge-epic

#8050 FOUR-22068: After the conflict need review the seeders for create default-email-task-notification
  ProcessMaker/Repositories/TokenRepository.php
  database/processes/screens/default-email-task-notification.json
  database/seeders/DatabaseSeeder.php
  database/seeders/ScreenEmailSeeder.php
Labels: merge-epic

#8046 bugfix/FOUR-21511 Unable to reassign when Assignment rule is based on expressions
  ProcessMaker/Models/ProcessRequestToken.php
Labels: PO Backlog Bug, no-fix-version

#8054 Preview file is not visible in form in a request completed
  resources/views/requests/show.blade.php
Labels: RC1, 4.13.2

#8035 bugfix/FOUR-21960 `Custom font` field is empty when `default font` is selected
  ProcessMaker/Http/Controllers/Api/CssOverrideController.php
  resources/js/admin/cssOverride/components/SiteDesign.vue
Labels: RC1, 4.13.2

#8055 FOUR-22097: download file is not displayed in form completed cases
  resources/jscomposition/system/table/cell/CollapseFormCell.vue
  resources/views/cases/edit.blade.php
Labels: RC1, 4.13.2

#8045 FOUR-22048 floating buttons have a strange behavior when the cursor is over them
  resources/js/tasks/components/TaskListRowButtons.vue
  resources/js/tasks/components/TasksList.vue
Labels: RC1, 4.13.2

#8042 bugfix/FOUR-21980: Cancel button does not clear the data in Create user form
  resources/js/admin/users/index.js
Labels: RC1, 4.13.2

#8041 bugfix/FOUR-21978 update the counter when the process info is collapsed
  resources/js/processes-catalogue/components/ProcessCollapseInfo.vue
  resources/js/processes-catalogue/components/ProcessHeader.vue
  resources/js/processes-catalogue/components/ProcessOptions.vue
Labels: 4.12.3, RC1

#8031 Resolve template creation on recent assets page
  resources/js/processes/designer/RecentAssetsList.vue
Labels: RC2, 4.13.1

#8022 FOUR-21936: Error 404 when importing old processes with sub processes
  ProcessMaker/Http/Controllers/Api/ProcessController.php
Labels: RC1, 4.13.2

#8016 Cannot create a pmblock with the language translation Português and Na Vosa Vakaviti (Fijian)
  resources/js/bootstrap.js
  resources/js/processes/screen-builder/screen.vue
Labels: RC1, 4.13.2

#8024 FOUR-21930 when enabling or disabling the SSO "Allow Standard Login" option the change is not immediate
  ProcessMaker/Observers/SettingObserver.php
  tests/Feature/Api/SettingAuthTest.php
Labels: 4.14.0, RC1

#8058 FOUR-22103: Oops! page not found appears when refreshing the browser in files cases
  resources/jscomposition/cases/casesDetail/components/CaseDetail.vue
  resources/views/cases/edit.blade.php
  routes/web.php
Labels: 4.14.0, RC1
