Repository ProcessMaker/processmaker, pull requests merged in 2025-04, with the labels that each got.

#8148 observation/FOUR-23646: Server Error iin Home page with user with dashboard delete, while the session is active
  resources/js/tasks/components/ParticipantHomeScreen.vue
  resources/js/tasks/components/ProcessesDashboardsMenu.vue
Labels: RC1, 4.14.2

#8128 FOUR-23563: When the user import a process or open and old processes the toogle Assigne and Due is enable per default
  resources/js/processes/modeler/components/inspector/TaskNotifications.vue
  resources/js/processes/modeler/initialLoad.js
  resources/js/processes/modeler/modelerInit.js
Labels: RC1, 4.14.2

#8142 observation/FOUR-23365 Quick Fill is not working for requests from Launch pad
  resources/js/tasks/components/QuickFillPreview.vue
Labels: RC1, 4.14.2

#8137 FOUR-22407: Collection record control not updating when editing from launchpad preview
  resources/js/tasks/api/index.js
  resources/js/tasks/loaderPreview.js
  resources/js/tasks/preview.js
  resources/js/tasks/utils/index.js
  resources/js/tasks/variables/index.js
Labels: RC1, 4.14.2

#8143 FOUR-23540: "Error Loading items" in Available columns in Saved searc…
  ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php
  tests/Feature/Api/V1_1/ProcessVariableControllerTest.php
Labels: RC1, 4.14.2

#8147 observation/FOUR-23642: Some assets do not have the `Add to bundle` option
  ProcessMaker/Enums/ExporterMap.php
  ProcessMaker/Models/BundleAsset.php
  devhub/pm-font/svg/pm-block.svg
  resources/fonts/pm-font/index.html
  resources/fonts/pm-font/processmaker-font.css
  resources/fonts/pm-font/processmaker-font.eot
  resources/fonts/pm-font/processmaker-font.less
  resources/fonts/pm-font/processmaker-font.module.less
  resources/fonts/pm-font/processmaker-font.scss
  resources/fonts/pm-font/processmaker-font.styl
  resources/fonts/pm-font/processmaker-font.svg
  resources/fonts/pm-font/processmaker-font.symbol.svg
  resources/fonts/pm-font/processmaker-font.ttf
  resources/fonts/pm-font/processmaker-font.woff
  resources/fonts/pm-font/processmaker-font.woff2
  resources/fonts/pm-font/symbol.html
  resources/fonts/pm-font/unicode.html
  resources/js/admin/devlink/components/assetTypes.js
Labels: RC1, 4.14.2

#8151 FOUR-23643 Fix migration issue
  database/migrations/2025_02_26_194048_modify_client_secret_in_dev_links_table.php
Labels: RC1, 4.14.2, answered

#8153 devLink > Options are Duplicate
  resources/js/admin/devlink/components/BundleSettingsModal.vue
Labels: RC1, 4.14.2

#8155 FOUR-23699 Fix User/groups > Home Page field does not works correctly when URL Redirect is selected
  ProcessMaker/Http/Controllers/HomeController.php
  tests/Feature/HomeControllerTest.php
Labels: RC1, 4.14.2

#8154 FOUR-23689: Cannot read properties of null (reading 'colorScheme') Error with chart without data in Launchpad chart
  resources/js/processes-catalogue/components/charts/ListChart.vue
Labels: RC1, 4.14.2

#8152 FOUR-24658 - Fix css config overrides
  ProcessMaker/Jobs/CompileSass.php
  ProcessMaker/Repositories/SettingsConfigRepository.php
  helpers.php
  tests/Repositories/SettingsConfigRepositoryTest.php
Labels: RC1, 4.14.2

#8162 observation/FOUR-23694 when settings configurations were added without any asset in the bundle then reinstall or update are not working.
  ProcessMaker/Models/Bundle.php
  tests/Model/DevLinkTest.php
Labels: RC1, 4.14.2

#8168 bugfix/FOUR-23723 added an new param for redirectListener
  ProcessMaker/Listeners/HandleRedirectListener.php
  ProcessMaker/Models/ProcessRequest.php
Labels: RC1, 4.14.2

#8166 FOUR-23386: Implement redirection improvement
  ProcessMaker/Listeners/HandleEndEventRedirect.php
Labels: merge-epic

#8164 FOUR-23692 - Launchpad: The Active columns remains the old configuration in launch pad
  resources/js/components/shared/LaunchpadSettingsModal.vue
  resources/js/processes-catalogue/components/ProcessInfo.vue
Labels: hold, version-tbd, SavedSearch

#8091 FOUR-23768: Fix laravel 11 tests
  .gitignore
  ProcessMaker/Console/Commands/CreateDataLakeViews.php
  ProcessMaker/Observers/SettingObserver.php
  phpunit.xml
  tests/Feature/Api/BoundaryEventsTest.php
  tests/Feature/Api/CallActivityTest.php
  tests/Feature/Api/TaskAssignmentByVariableTest.php
  tests/Feature/Api/TaskAssignmentExecutionTest.php
  tests/Feature/Api/UsersTest.php
  tests/Feature/Cache/SettingCacheTest.php
  tests/Feature/Cases/CaseStartedTest.php
  tests/Feature/Upgrade/PopulateCasesParticipatedTest.php
  tests/TestCase.php
  tests/unit/ProcessMaker/Cache/Monitoring/RedisMetricsManagerTest.php
Labels: hold, RC1, 4.14.2

#8172 Fix HTTP client timeout
  ProcessMaker/ScriptRunners/ScriptMicroserviceRunner.php
Labels: RC1, 4.14.2

#8170 observation/FOUR-23761 Response error with API calls using Password Grant authentication
  ProcessMaker/Providers/AuthServiceProvider.php
Labels: RC1, 4.14.2

#8157 [CRITICAL] Session Token Does Not Expire
  ProcessMaker/Http/Kernel.php
  ProcessMaker/Http/Middleware/LaravelTokenMiddleware.php
Labels: RC1, 4.14.2

#8149 Security/FOUR-22502: [HIGH] Host Header Injection
  ProcessMaker/Http/Kernel.php
  ProcessMaker/Http/Middleware/TrustHosts.php
  tests/Feature/Http/Middleware/TrustHostsTest.php
Labels: RC1, 4.14.2

#8173 FOUR-22970 add Email Listener by default
  ProcessMaker/Models/Setting.php
  resources/js/admin/settings/components/SettingChoice.vue
  resources/js/admin/settings/components/SettingsMain.vue
  resources/views/admin/settings/index.blade.php
Labels: merge-epic

#8180 FOUR-23765: Update the message error when the name exists
  ProcessMaker/Http/Controllers/Api/SettingController.php
  tests/Feature/Api/SettingsTest.php
Labels: merge-epic

#8181 FOUR-23805: Update the text of modal to create a URL and validate the URL
  resources/js/admin/settings/components/ModalWhiteList.vue
  resources/lang/en.json
Labels: merge-epic

#8195 FOUR-23814: Available Columns, in Edit Task Column, in Launchpad Settings shows all columns in bulk at the bottom
  resources/js/components/shared/Column.vue
  resources/js/components/shared/ColumnChooser.vue
  resources/js/components/shared/LaunchpadSettingsModal.vue
Labels: RC1, Beta3, 4.14.2

#8197 FOUR-23895: The SSO configurations are not showing all the information
  ProcessMaker/Models/Setting.php
Labels: merge-epic

#8194 FOUR-23423 S2: BE - A list of users from the groups or users able to …
  ProcessMaker/Http/Controllers/Api/UserController.php
  ProcessMaker/Models/Process.php
  resources/js/tasks/components/taskPreview/TaskPreviewAssignment.vue
  tests/Feature/Api/UsersTest.php
Labels: merge-epic

#8208 FOUR-23484: S4:FE-Process Info update & Add the UI component to show the total cases per stage
  resources/js/processes-catalogue/components/ProcessCollapseInfo.vue
  resources/js/processes-catalogue/components/ProcessInfo.vue
  resources/js/processes-catalogue/components/ProcessOptions.vue
  resources/js/processes-catalogue/components/optionsMenu/ProcessDescription.vue
  resources/js/processes-catalogue/components/progressBar/ProgressBar.vue
  resources/js/processes-catalogue/components/progressBar/ProgressBarSection.vue
  resources/js/processes-catalogue/components/progressBar/ProgressInfo.vue
  resources/js/processes-catalogue/components/slideProcessInfo/SlideProcessInfo.vue
Labels: merge-epic
