Repository ProcessMaker/processmaker, pull requests merged in 2025-09, with the labels that each got.

#8496 FOUR-24108:Reassignment form is not hidden in tasks where the "Allow Reassignment" option is not enabled.
  resources/js/tasks/components/PreviewMixin.js
Labels: merge-epic

#8458 FOUR-25925: Error in the chart of the list type, when we add "Assigne" in a self-service status save search
  ProcessMaker/Models/ProcessRequestToken.php
  tests/unit/ProcessMaker/FilterTest.php
Labels: Beta1, 4.15.7

#8468 FOUR-25761:UI: There is no synchronization with the "i" button
  resources/js/processes-catalogue/components/home/ProcessInfo.vue
  resources/js/processes-catalogue/components/home/TceDistributionCollege.vue
  resources/js/processes-catalogue/components/home/TceDistributionGrants.vue
  resources/js/processes-catalogue/components/home/TceDistributionStudent.vue
  resources/js/processes-catalogue/components/home/utils/processInfo.js
Labels: Beta1, 4.15.7

#8469 FOUR-25910: Old processes do not update the progress bar status (In progress and completed)
  upgrades/2025_08_25_114401_populate_cases_participated_stage_and_progress.php
Labels: Beta1, 4.15.7

#8470 FOUR-25952:Hide the Stage aggregation option from the modeler
  ProcessMaker/Http/Controllers/Process/ModelerController.php
  resources/js/processes/modeler/components/inspector/StageManager.vue
  resources/views/processes/modeler/index.blade.php
Labels: Beta1, 4.15.7

#8519 FOUR-26361: Allow upload text/plain mime type for CSV files.
  config/files.php
Labels: Beta3, 4.15.7

#8523 FOUR-26546:Arrows are not displayed in the carousel when Process information is opened
  resources/js/processes-catalogue/components/CarouselSlide.vue
Labels: Beta4, 4.15.7

#8513 Add `package-sis-integrations` to composer.json custom package array
  composer.json
Labels: 4.15.7

#8520 Fix Incorrect "Create Template" Modal Display for Screens
  public/builds/login/js/app-login.js
  public/builds/login/js/manifest.js
  public/builds/login/js/vendor.js
  public/images/flowGenieIcon.svg
  public/images/wizard-icon.svg
  resources/js/processes/designer/RecentAssetsList.vue
Labels: 4.15.7

#8527 FOUR-26562 FIX Process variable, not assigned to the user by its ID
  ProcessMaker/Models/Process.php
  helpers.php
  tests/Feature/Api/TaskAssignmentByVariableTest.php
Labels: 4.15.7, failingeks
