Repository ProcessMaker/processmaker, pull requests merged in 2025-07, with the labels that each got.

#8342 FOUR-24778: The columns data.someFields does not show the correct information
  resources/js/processes-catalogue/components/home/CustomHomeTableSection/CustomHomeTableSection.vue
  resources/jscomposition/base/table/TCell.vue
Labels: merge-epic

#8340 FOUR-24972: There is not scroll in "Completed & Form" Cases
  resources/jscomposition/cases/casesDetail/components/CaseDetail.vue
  resources/jscomposition/cases/casesDetail/components/Tabs.vue
Labels: merge-epic

#8348 FOUR-24983: It is possible to add more than 8 stages in modeler
  resources/js/processes/modeler/components/inspector/StageList.vue
  resources/js/processes/modeler/components/inspector/StageManager.vue
Labels: merge-epic

#8338 FOUR-25078 Response time in data connector resources has increased afer the upgrade to version 4.14
  ProcessMaker/Http/Controllers/Api/SettingController.php
  ProcessMaker/Repositories/SettingsConfigRepository.php
  tests/Repositories/SettingsConfigRepositoryTest.php
Labels: Beta1, 4.15.3

#8347 FOUR-24981: It is not possible to start a case if the process has large stage name
  resources/js/processes/modeler/components/inspector/StageItem.vue
  resources/js/processes/modeler/components/inspector/StageList.vue
Labels: merge-epic

#8351 FOUR-25243: Show the Email Screen in the Screen list
  ProcessMaker/Models/Screen.php
  database/processes/screens/default-email-task-notification.json
  database/seeders/ScreenEmailSeeder.php
  tests/unit/ScreenEmailSeederTest.php
  upgrades/2025_07_08_151252_update_default_email_task_notification_screen_category.php
Labels: merge-epic

#8358 FOUR-25242: Prevent deletion of DEFAULT_EMAIL_TASK_NOTIFICATION
  ProcessMaker/Http/Controllers/Api/ScreenController.php
Labels: merge-story

#8363 FOUR-25240:Implement property linkDisplayStyle = [LINK, BUTTON]
  resources/img/arrow_top_right.svg
Labels: merge-story

#8324 FOUR-24952: JSON Optimization
  ProcessMaker/Http/Controllers/Api/TaskController.php
  ProcessMaker/Providers/JsonOptimizerServiceProvider.php
  ProcessMaker/Support/JsonOptimizer.php
  config/app.php
  docs/json-optimization.md
  helpers.php
  tests/Fixtures/json_optimizer_test_example.json
  tests/unit/ProcessMaker/JsonOptimizerTest.php
Labels: Beta1, 4.15.4

#8326 FOUR-25042: The Priority and Draft tab are moved to the Inbox, when you click the browser's reloaded this page
  resources/js/tasks/components/ParticipantHomeScreen.vue
  resources/js/tasks/mixins/TasksMixin.js
Labels: Beta1, 4.15.4

#8360 FOUR-25271: Total cases does not match with cases started in launchpad to Grant chart
  ProcessMaker/Models/Process.php
Labels: merge-epic

#8365 FOUR-24887: UI: the progress Bar needs work when the stages are the defaults
  ProcessMaker/Repositories/CaseParticipatedRepository.php
  ProcessMaker/Repositories/CaseRepository.php
Labels: merge-epic

#8368 FOUR-25246: Delete the Backend changes related to the Task Notification Email
  ProcessMaker/Repositories/TokenRepository.php
  tests/Feature/TaskControllerTest.php
Labels: merge-story

#8376 FOUR-25222: There is no synchronization with the 'i' button and the form process info when it is open or closed
  resources/js/processes-catalogue/components/ProcessCollapseInfo.vue
  resources/js/processes-catalogue/components/ProcessInfo.vue
Labels: merge-epic

#8377 FOUR-25269: In Grant chart the tabs In progress and Completed does not listed any request
  ProcessMaker/Models/Process.php
  resources/js/processes-catalogue/components/home/TceDistributionGrants.vue
  tests/Feature/Api/ProcessControllerTest.php
Labels: merge-epic

#8378 FOUR-24578: The Stage for the End Event is not registered and the progress is not showing correctly
  ProcessMaker/Http/Controllers/CasesController.php
Labels: merge-epic

#8379 Fix data source scripts constraint violation during Guided Template script import
  ProcessMaker/ImportExport/Exporters/ScriptExporter.php
Labels: Beta4, 4.15.4

#8372 FOUR-25224: [STORY] Notifications should be driven by standard email notification configuration
  ProcessMaker/Http/Controllers/Process/ModelerController.php
  resources/js/processes/modeler/modelerInit.js
  resources/views/processes/modeler/index.blade.php
Labels: merge-epic

#8373 FOUR-25225: [STORY] Hide Task Notification Email option in user profile
  ProcessMaker/Repositories/TokenRepository.php
  resources/views/shared/users/sidebar.blade.php
  tests/Feature/TaskControllerTest.php
Labels: merge-epic

#8381 FOUR-25427: Notification update the screen with the correct variables
  database/processes/screens/default-email-task-notification.json
Labels: merge-story

#8396 FOUR-25426:UI: There is no validation of variables in Stage Aggregation
  resources/js/processes/modeler/components/inspector/AgregationProperty.vue
Labels: merge-epic

#8399 FOUR-25356: UI: Review the render of TCE Dasboards
  resources/js/processes-catalogue/components/ProcessesCatalogue.vue
  resources/js/tasks/components/ParticipantHomeScreen.vue
  resources/js/tasks/components/ProcessesDashboardsMenu.vue
  resources/jscomposition/base/ui/CollapsableContainer.vue
  resources/views/processes-catalogue/index.blade.php
  resources/views/tasks/index.blade.php
Labels: merge-epic
