Repository ProcessMaker/processmaker, pull requests merged in 2025-05, with the labels that each got.

#8214 FOUR-24213: Errors related to templates in builds and CICD
  ProcessMaker/Jobs/SyncDefaultTemplates.php
Labels: Beta1, 4.15.0

#8205 FOUR-23478: S2: FE - Add new columns and prepare structure in the tables
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/CasesController.php
  ProcessMaker/Http/Resources/V1_1/CaseResource.php
  ProcessMaker/Listeners/BpmnSubscriber.php
  ProcessMaker/Models/CaseParticipated.php
  ProcessMaker/Models/CaseStarted.php
  ProcessMaker/Models/ProcessRequestToken.php
  ProcessMaker/Repositories/CaseApiRepository.php
  ProcessMaker/Repositories/CaseRepository.php
  ProcessMaker/Repositories/CaseUtils.php
  ProcessMaker/Repositories/TokenRepository.php
  ProcessMaker/Traits/ProcessMapTrait.php
  database/migrations/2025_04_23_162421_add_stages_to_processes_and_process_versions.php
  database/migrations/2025_04_23_183734_add_stage_id_and_stage_name_to_process_request_tokens.php
  database/migrations/2025_04_23_183839_add_stage_id_and_stage_name_to_process_request.php
  database/migrations/2025_04_23_184251_add_stage_id_and_stage_name_to_cases_participated.php
  database/migrations/2025_04_23_184327_add_stage_id_and_stage_name_to_cases_started.php
  database/migrations/2025_04_25_222214_add_stages_table.php
  tests/Feature/Api/ProcessControllerTest.php
  tests/Feature/CasesControllerTest.php
Labels: merge-epic

#8220 FOUR-24219: Update the structure of tables: process_request and cases_started and cases_participated
  ProcessMaker/Http/Controllers/CasesController.php
  ProcessMaker/Http/Resources/V1_1/CaseResource.php
  ProcessMaker/Models/CaseParticipated.php
  ProcessMaker/Models/CaseStarted.php
  ProcessMaker/Repositories/CaseApiRepository.php
  ProcessMaker/Repositories/CaseRepository.php
  ProcessMaker/Repositories/CaseUtils.php
  ProcessMaker/Repositories/TokenRepository.php
  database/migrations/2025_04_23_183734_add_stage_id_and_stage_name_to_process_request_tokens.php
  database/migrations/2025_04_23_183839_add_stage_id_and_stage_name_to_process_request.php
  database/migrations/2025_04_23_184251_add_stage_id_and_stage_name_to_cases_participated.php
  database/migrations/2025_04_23_184327_add_stage_id_and_stage_name_to_cases_started.php
  tests/Feature/CasesControllerTest.php
Labels: merge-epic

#8221 FOUR-23485: Create a new API to return total cases per Stage
  ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php
  ProcessMaker/Traits/ProcessTrait.php
  resources/js/processes-catalogue/components/ProcessInfo.vue
  resources/js/processes-catalogue/components/progressBar/ProgressBarSection.vue
  resources/js/processes-catalogue/components/progressBar/ProgressInfo.vue
  tests/Feature/Api/ProcessLaunchpadTest.php
Labels: merge-epic

#8222 FOUR-23483: Add in Details the Stage and bar
  ProcessMaker/Http/Controllers/CasesController.php
  resources/jscomposition/cases/casesDetail/components/StageBar.vue
  resources/jscomposition/cases/casesDetail/edit.js
  resources/jscomposition/cases/casesDetail/variables/index.js
  resources/views/cases/edit.blade.php
Labels: merge-epic

#8224 FOUR-24229: Get information to show status of the stages in the Case Progress Bar control
  ProcessMaker/Http/Controllers/Api/CaseController.php
  config/app.php
  routes/api.php
  tests/Feature/CasesControllerTest.php
Labels: merge-epic

#8231 FOUR-24148: UI related Process Info - Carousel (refactor)
  resources/js/processes-catalogue/components/BaseChart.vue
  resources/js/processes-catalogue/components/CarouselSlide.vue
  resources/js/processes-catalogue/components/ProcessInfo.vue
  resources/js/processes-catalogue/components/ProcessOptions.vue
  resources/js/processes-catalogue/components/ProcessesCarousel.vue
  resources/js/processes-catalogue/components/mixins/CarouselMixin.js
  resources/js/processes-catalogue/components/slideProcessInfo/SlideProcessInfo.vue
  resources/views/tasks/index.blade.php
Labels: merge-epic

#8232 FOUR-24233:The Summary tab needs to show per default
  ProcessMaker/Http/Controllers/CasesController.php
  resources/jscomposition/cases/casesDetail/components/CaseDetail.vue
  resources/jscomposition/cases/casesDetail/variables/index.js
  resources/views/cases/edit.blade.php
Labels: merge-epic

#8242 FOUR-24227: Adding changes in order to get the status: Done, In progres, Pending
  ProcessMaker/Http/Controllers/Api/CaseController.php
  tests/Feature/CasesControllerTest.php
Labels: merge-epic

#8239 FOUR-24089 : S12: Create the view to show a dashboard with the components related to "Financial Aid - College Dashboard"
  resources/js/components/shared/LaunchpadSettingsModal.vue
  resources/js/processes-catalogue/components/Process.vue
  resources/js/processes-catalogue/components/ProcessCollapseInfo.vue
  resources/js/processes-catalogue/components/api/index.js
  resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButton.vue
  resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonGroup.vue
  resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonHome.vue
  resources/js/processes-catalogue/components/home/ButtonGroup/BaseCardButton.vue
  resources/js/processes-catalogue/components/home/ButtonGroup/BaseCardButtonGroup.vue
  resources/js/processes-catalogue/components/home/CustomHomeScreen.vue
  resources/js/processes-catalogue/components/home/CustomHomeTableSection/CustomHomeTableSection.vue
  resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButton.vue
  resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButtonGroup.vue
  resources/js/processes-catalogue/components/home/ProcessInfo.vue
  resources/js/processes-catalogue/components/home/TceDistributionCollege.vue
  resources/js/processes-catalogue/components/home/TceDistributionGrants.vue
  resources/js/processes-catalogue/components/home/TceDistributionStudent.vue
  resources/js/processes-catalogue/components/home/config/columns.js
  resources/js/processes-catalogue/components/home/config/index.js
  resources/js/processes-catalogue/components/home/config/metrics.js
  resources/js/processes-catalogue/components/home/config/requestDefaultColumns.js
  resources/js/processes-catalogue/components/variables/index.js
  resources/jscomposition/system/table/cell/ProgressBarCell.vue
  resources/jscomposition/system/table/cell/index.js
  resources/views/processes-catalogue/index.blade.php
  resources/views/tasks/index.blade.php
Labels: merge-epic

#8243 FOUR-24227: Add in the display screen a New control - Case Progress Bar
  resources/js/processes/screen-builder/typeDisplay.js
  resources/js/processes/screen-builder/typeForm.js
  resources/views/cases/edit.blade.php
Labels: merge-epic

#8245 FOUR-24430: CI Unit Test are given error SyncDefaultTemplates.php:79
  ProcessMaker/Jobs/SyncDefaultTemplates.php
  tests/Jobs/SyncDefaultTemplatesTest.php
Labels: 4.15.0

#8234 FOUR-22734 S1: The Publish and save process needs to save the stages
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Models/Process.php
  ProcessMaker/Models/ProcessVersion.php
  devhub/pm-font/svg/check-circle-blue.svg
  resources/fonts/pm-font/index.html
  resources/fonts/pm-font/processmaker-font.css
  resources/fonts/pm-font/processmaker-font.eot
  resources/fonts/pm-font/processmaker-font.less
  resources/fonts/pm-font/processmaker-font.module.less
  resources/fonts/pm-font/processmaker-font.scss
  resources/fonts/pm-font/processmaker-font.styl
  resources/fonts/pm-font/processmaker-font.svg
  resources/fonts/pm-font/processmaker-font.symbol.svg
  resources/fonts/pm-font/processmaker-font.ttf
  resources/fonts/pm-font/processmaker-font.woff
  resources/fonts/pm-font/processmaker-font.woff2
  resources/fonts/pm-font/symbol.html
  resources/fonts/pm-font/unicode.html
  resources/js/processes/modeler/components/inspector/StageItem.vue
  resources/js/processes/modeler/components/inspector/StageList.vue
  resources/js/processes/modeler/components/inspector/StageManager.vue
  routes/api.php
  tests/Feature/Api/ProcessControllerTest.php
Labels: merge-epic

#8247 FOUR-24234: API Return information for the Stages and Metrics
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Models/Process.php
  routes/api.php
  tests/Feature/Api/ProcessControllerTest.php
Labels: merge-epic

#8251 FOUR-24448: Consider use cases for return Default Stages per Case and case_number not required
  ProcessMaker/Http/Controllers/Api/CaseController.php
  routes/api.php
  tests/Feature/CasesControllerTest.php
Labels: merge-epic

#8252 FOUR-24450: Add indexes to improve the queries about stage_id
  database/migrations/2025_05_19_205653_add_index_stage_id_for_requests_cases_and_tokens.php
Labels: merge-epic

#8199 FOUR-23865: Fix loading tasks in saved search with process with html entities
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  tests/Feature/ProcessHtmlTest.php
  tests/Fixtures/process_with_html.bpmn
Labels: RC1, 4.15.0

#8177 FOUR-22580: [SUMMER 25] IFrame Whitelist Configs
  ProcessMaker/Http/Controllers/Api/SettingController.php
  config/session.php
  resources/js/admin/settings/components/ModalWhiteList.vue
  resources/js/admin/settings/components/SettingsListing.vue
  resources/lang/en.json
  routes/api.php
  tests/Feature/Api/SettingsTest.php
  upgrades/2025_03_31_140423_add_menu_frame_whitelist.php
Labels: summer-2025, 4.15.0

#8259 FOUR-23607:Add a Link to configure cases column & show the component to configure columns
  resources/js/components/shared/EditColumnModal.vue
  resources/js/components/shared/LaunchpadSettingsModal.vue
  resources/js/processes-catalogue/components/ProcessCollapseInfo.vue
  resources/js/processes-catalogue/components/ProcessInfo.vue
  resources/js/processes-catalogue/components/ProcessTab.vue
  resources/lang/en.json
Labels: merge-epic

#8265 FOUR-24336:Create a new View when a case is open and the TCE_CUSTOMIZATION_ENABLED is enabled
  resources/jscomposition/cases/casesDetail/components/CaseDetail.vue
Labels: merge-epic

#8258 FOUR-23891: UI: The Assign button needs to block for avoid send the comments a more than one time
  resources/js/tasks/components/taskPreview/TaskPreviewAssignment.vue
Labels: merge-epic, qa-observation

#8256 FOUR-23482 S2: BE - Populate the STAGE and PROGRESS columns in run ca…
  ProcessMaker/Http/Controllers/ProcessesCatalogueController.php
  ProcessMaker/Listeners/BpmnSubscriber.php
  ProcessMaker/Models/ProcessRequestToken.php
  ProcessMaker/Repositories/CaseParticipatedRepository.php
  ProcessMaker/Repositories/CaseRepository.php
  ProcessMaker/Repositories/TokenRepository.php
  ProcessMaker/Traits/ProcessMapTrait.php
  ProcessMaker/Traits/ProcessTrait.php
  helpers.php
  resources/js/processes/modeler/components/inspector/StageItem.vue
  resources/js/processes/modeler/components/inspector/StageList.vue
  resources/js/processes/modeler/components/inspector/StageManager.vue
  tests/Feature/Api/ProcessControllerTest.php
  tests/Feature/Api/ProcessLaunchpadTest.php
  tests/Model/ProcessRequestTokenTest.php
Labels: merge-epic

#8257 FOUR-24454 : S12: Update/Adjustments some behaviors the Dashboard
  resources/js/processes-catalogue/components/api/index.js
  resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButton.vue
  resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonGroup.vue
  resources/js/processes-catalogue/components/home/ArrowButtonGroup/ArrowButtonHome.vue
  resources/js/processes-catalogue/components/home/ButtonGroup/BaseCardButton.vue
  resources/js/processes-catalogue/components/home/ButtonGroup/BaseCardButtonGroup.vue
  resources/js/processes-catalogue/components/home/CustomHomeTableSection/CustomHomeTableSection.vue
  resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButton.vue
  resources/js/processes-catalogue/components/home/PercentageButtonGroup/PercentageCardButtonGroup.vue
  resources/js/processes-catalogue/components/home/TceDistributionCollege.vue
  resources/js/processes-catalogue/components/home/TceDistributionGrants.vue
  resources/js/processes-catalogue/components/home/TceDistributionStudent.vue
  resources/js/processes-catalogue/components/home/config/metrics.js
  resources/js/tasks/components/ParticipantHomeScreen.vue
  tailwind.config.js
Labels: merge-epic

#8267 FOUR-22600: [DEPENDENCY] Stages configuration merged into FOUR-22605
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Http/Controllers/ProcessesCatalogueController.php
  ProcessMaker/Listeners/BpmnSubscriber.php
  ProcessMaker/Models/Process.php
  ProcessMaker/Models/ProcessRequestToken.php
  ProcessMaker/Models/ProcessVersion.php
  ProcessMaker/Repositories/CaseParticipatedRepository.php
  ProcessMaker/Repositories/CaseRepository.php
  ProcessMaker/Repositories/TokenRepository.php
  ProcessMaker/Traits/ProcessMapTrait.php
  ProcessMaker/Traits/ProcessTrait.php
  devhub/pm-font/svg/check-circle-blue.svg
  helpers.php
  resources/fonts/pm-font/index.html
  resources/fonts/pm-font/processmaker-font.css
  resources/fonts/pm-font/processmaker-font.eot
  resources/fonts/pm-font/processmaker-font.less
  resources/fonts/pm-font/processmaker-font.module.less
  resources/fonts/pm-font/processmaker-font.scss
  resources/fonts/pm-font/processmaker-font.styl
  resources/fonts/pm-font/processmaker-font.svg
  resources/fonts/pm-font/processmaker-font.symbol.svg
  resources/fonts/pm-font/processmaker-font.ttf
  resources/fonts/pm-font/processmaker-font.woff
  resources/fonts/pm-font/processmaker-font.woff2
  resources/fonts/pm-font/symbol.html
  resources/fonts/pm-font/unicode.html
  resources/js/processes/modeler/components/inspector/StageItem.vue
  resources/js/processes/modeler/components/inspector/StageList.vue
  resources/js/processes/modeler/components/inspector/StageManager.vue
  routes/api.php
  tests/Feature/Api/ProcessControllerTest.php
  tests/Feature/Api/ProcessLaunchpadTest.php
  tests/Model/ProcessRequestTokenTest.php
Labels: merge-epic

#8262 FOUR-24476: Review Clicked Links in Email are not working as expected
  ProcessMaker/Events/BaseEmailEvent.php
  ProcessMaker/Events/EmailComplaint.php
  ProcessMaker/Events/EmailDelivered.php
  ProcessMaker/Events/EmailLinkClicked.php
  ProcessMaker/Events/EmailSent.php
  ProcessMaker/Events/EmailViewed.php
  tests/Feature/Events/EmailEventTest.php
Labels: merge-epic

#8283 FOUR-24636: Error is showing in the API: api/1.0/cases/stages_bar/2
  ProcessMaker/Http/Controllers/Api/CaseController.php
  tests/Feature/Api/ProcessLaunchpadTest.php
Labels: merge-epic

#8261 FOUR-23828: It is possible to create Site name with blank spaces in IFrame white list
  resources/js/admin/settings/components/ModalWhiteList.vue
Labels: Beta2, 4.15.0, qa-observation

#8290 FOUR-24105:Cancel and Assignment buttons are not in the correct position in the Reassignment form
  resources/js/tasks/components/TasksPreview.vue
  resources/js/tasks/components/taskPreview/TaskPreviewAssignment.vue
Labels: merge-epic

#8292 FOUR-2445: S12: API - Return Metrics information
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  ProcessMaker/Models/Process.php
  tests/Feature/CasesControllerTest.php
Labels: merge-epic
