Repository ProcessMaker/processmaker, pull requests merged in 2025-01, with the labels that each got.

#7633 Bugfix/FOUR-18844: "Loading suggestion" keeps showing indefinitely in scripts
  resources/js/processes/scripts/components/GenerateScriptTextPrompt.vue
Labels: PO Backlog Bug

#7869 FOUR-20583: Updating observations
  resources/js/next/config/i18n.js
  resources/js/next/config/notifications.js
  resources/js/next/config/openAI.js
  resources/js/next/config/processmaker.js
  resources/js/next/config/session.js
  resources/js/next/config/user.js
  resources/js/next/libraries/broadcast.js
  resources/js/next/modeler.js
  resources/js/next/monaco.js
  resources/js/next/screenBuilder.js
  resources/js/next/setupMain.js
  resources/js/tasks/loaderEdit.js
  resources/js/tasks/loaderMain.js
  resources/js/tasks/loaderPreview.js
  resources/jscomposition/cases/casesDetail/loader.js
  resources/jscomposition/cases/casesMain/loader.js
Labels: winter-2025

#7887 FOUR-20673: Create a new column to know if an email was sent
  ProcessMaker/Models/ProcessRequestToken.php
  ProcessMaker/Repositories/TokenRepository.php
  database/migrations/2025_01_10_183851_add_is_emailsent_column_for_process_request_tokens_table.php
Labels: spring-2025, merge-epic

#7881 FOUR-14263: The button SAVE is not working in TEST option
  ProcessMaker/Traits/TaskResourceIncludes.php
Labels: PO Backlog Bug, no-fix-version

#7824 FOUR-20281: [WINTER] Remove fades on tab switching
  resources/views/admin/users/index.blade.php
  resources/views/components/categorized_resource.blade.php
  resources/views/processes/edit.blade.php
  resources/views/processes/screens/edit.blade.php
  resources/views/processes/scripts/edit.blade.php
  resources/views/processes/signals/edit.blade.php
  resources/views/requests/index.blade.php
  resources/views/requests/show.blade.php
  resources/views/requests/showMobile.blade.php
  resources/views/tasks/edit.blade.php
  resources/views/tasks/index.blade.php
  resources/views/templates/configure.blade.php
Labels: 4.13.0, winter-2025

#7860 FOUR-20337: [WINTER] Speed up In-Flight Modeler UI Component
  ProcessMaker/Http/Controllers/CasesController.php
  ProcessMaker/Http/Controllers/RequestController.php
  ProcessMaker/Traits/ProcessMapTrait.php
  resources/js/requests/show.js
  resources/jscomposition/cases/casesDetail/components/CaseDetail.vue
  resources/jscomposition/cases/casesDetail/components/MapLegend.vue
  resources/jscomposition/cases/casesDetail/components/NewOverview.vue
  resources/jscomposition/cases/casesDetail/variables/index.js
  resources/views/cases/edit.blade.php
  resources/views/requests/show.blade.php
Labels: 4.13.0, winter-2025

#7686 Task/FOUR-19875: aria-label property is the same in all options in the select list component generating unexpected behaviors for screen readers
  resources/lang/en.json
Labels: 4.13.0

#7706 Task/FOUR-20032-fall: Hide FlowGenie from Ellucian's servers
  resources/js/processes/designer/Assets.vue
  resources/js/processes/designer/RecentAssets.vue
Labels: 4.13.0

#7873 Reload the data tab when the task changes
  resources/views/tasks/edit.blade.php
Labels: PO Backlog Bug, no-fix-version

#7805 FOUR-21173: Admin Settings is not translating
  resources/lang/en.json
  resources/lang/es.json
Labels: PO Backlog Bug, 4.13.0

#7871 FOUR-21445 email field cannot be updated for users imported from AD or SAML
  ProcessMaker/Http/Controllers/Admin/UserController.php
  ProcessMaker/Http/Controllers/ProfileController.php
Labels: PO Backlog Bug, no-fix-version

#7839 FOUR-21290: Fix Unable to Create Processes from Guided Templates
  ProcessMaker/Http/Controllers/Api/TemplateController.php
  ProcessMaker/Models/Template.php
Labels: PO Backlog Bug, no-fix-version

#7890 FOUR-15298: [37189] Session Inactivity Option
  resources/js/bootstrap.js
  resources/js/components/Session.vue
  resources/js/timeout.js
Labels: PO Backlog Bug, no-fix-version

#7920 FOUR-20598: Horizontal adaptation define a minimum width of the columns
  resources/jscomposition/base/table/BaseTable.vue
  resources/jscomposition/base/table/TCell.vue
  resources/jscomposition/base/table/THeader.vue
  resources/jscomposition/base/table/composables/columnComposable.js
  resources/jscomposition/cases/casesDetail/components/TaskTable.vue
  resources/jscomposition/cases/casesDetail/config/columns.js
  resources/jscomposition/cases/casesMain/CasesDataSection.vue
  resources/jscomposition/cases/casesMain/config/columns.js
  resources/jscomposition/system/table/FilterableTable.vue
  resources/jscomposition/system/table/SortTable.vue
Labels: merge-epic

#7826 FOUR-21174: Case Title filter has number type
  resources/jscomposition/cases/casesMain/config/columns.js
Labels: PO Backlog Bug, 4.13.0

#7892 FOUR-20929: Implement ETag Caching
  ProcessMaker/Http/Kernel.php
  ProcessMaker/Http/Middleware/Etag/HandleEtag.php
  ProcessMaker/Http/Resources/Caching/EtagManager.php
  ProcessMaker/Http/Resources/V1_1/TaskResource.php
  ProcessMaker/Providers/ProcessMakerServiceProvider.php
  ProcessMaker/Providers/RouteServiceProvider.php
  ProcessMaker/Traits/TaskResourceIncludes.php
  config/etag.php
  docs/etag-caching.md
  routes/engine.php
  routes/v1_1/api.php
  tests/Feature/Etag/EtagManagerTest.php
  tests/Feature/Etag/HandleEtagCacheInvalidationTest.php
  tests/Feature/Etag/HandleEtagTest.php
  tests/k6/etag/config.js
  tests/k6/etag/detect-dynamic-endpoints.js
  tests/k6/etag/long-duration-test.js
  tests/k6/etag/performance-test.js
Labels: conflicts, 4.13.0

#7838 FOUR-21235 | Enforce File Upload Limit When Using Chunked File Upload Component
  ProcessMaker/Http/Kernel.php
  ProcessMaker/Http/Middleware/FileSizeCheck.php
  config/app.php
  tests/unit/FileSizeCheckTest.php
Labels: 4.12.3

#7919 FOUR-20680: Send an email when the task and taskManual has an assignee and the toogle in users is enable and register
  ProcessMaker/Mail/TaskActionByEmail.php
  ProcessMaker/Repositories/TokenRepository.php
  database/processes/screens/default-email-task-notification.json
  database/seeders/ScreenSystemSeeder.php
Labels: merge-epic

#7769 FOUR-19583: Cyclical group assignment stops users from being able to login
  ProcessMaker/Traits/HasAuthorization.php
  tests/Feature/PermissionsTest.php
Labels: 4.13.0, RC2

#7959 FOUR-21667 | "Edit Template” Link for Screen Templates Does Not Redirect to Edit Page in Screen Builder
  ProcessMaker/Http/Controllers/TemplateController.php
  resources/js/components/shared/ellipsisMenuActions.js
  resources/js/processes/screen-templates/mixins/navigationMixin.js
  resources/views/processes/screen-builder/showTemplate.blade.php
  routes/web.php
Labels: 4.13.0, RC2

#7960 Fix Screen Template Owner Display
  resources/js/processes/screen-templates/components/PublicTemplatesListing.vue
Labels: 4.13.0, RC2

#7963 Bugfix/FOUR-21504: Owner default name is not displayed in the Processes page
  resources/js/components/AvatarImage.vue
  resources/js/components/shared/FilterTableBodyMixin.js
  resources/js/processes/components/ProcessMixin.js
Labels: 4.13.0, RC2

#7955 FOUR-21631 select list does not show the field assigned to its data in web entry
  resources/js/processes/screen-builder/typeForm.js
Labels: 4.13.0, RC2

#7951 FOUR-17551:Scrollbar Position Issue When Navigating to Next Page
  resources/js/processes/screen-builder/screen.vue
  resources/js/tasks/edit.js
  resources/views/tasks/edit.blade.php
Labels: 4.13.0, winter-2025, RC2

#7944 FOUR-21624 There is not Clear draft in task detail
  resources/views/tasks/edit.blade.php
Labels: 4.13.0, RC2

#7950 FOUR-21622: There is not auto save in task details
  resources/js/tasks/edit.js
Labels: 4.13.0, RC2

#7967 Add script microservice status to about page
  ProcessMaker/Http/Controllers/AboutController.php
  resources/views/about/microservices.blade.php
Labels: 4.13.0, RC2

#7961 FOUR-21555 Performance backend improvements
  database/migrations/2025_01_29_205842_add_index_process_id_status_user_id_to_process_requests_table.php
Labels: 4.13.0, RC2
