Repository ProcessMaker/processmaker, pull requests merged in 2025-03, with the labels that each got.

#8069 FOUR-21934: Oopss page when entering "Open Process Launchpad" in Docusign Authorization
  resources/views/requests/show.blade.php
  resources/views/tasks/edit.blade.php
Labels: 4.13.2

#7968 FOUR-21556 Add support for coverage report in packages
  phpunit.package.xml
Labels: 4.14.0

#8071 Reconcile Element Destination vs Interstitial vs WE Completed Action
  resources/js/processes/modeler/components/inspector/ScreenSelect.vue
  resources/js/processes/modeler/components/inspector/TaskInterstitial.vue
  resources/js/processes/modeler/initialLoad.js
  resources/lang/de.json
  resources/lang/en.json
  resources/lang/es.json
  resources/lang/fr.json
Labels: 4.14.0

#8072 Script Task Metrics
  ProcessMaker/Jobs/RunScriptTask.php
  config/broadcasting.php
  resources/grafana/MainDashboard.json
Labels: 4.14.0

#8075 Participant Home Screen MERGE Epic/FOUR-20297-b into release-2025-spring
  ProcessMaker/Http/Controllers/Api/UserConfigurationController.php
  ProcessMaker/Http/Controllers/HomeController.php
  ProcessMaker/Http/Controllers/ProcessesCatalogueController.php
  ProcessMaker/Http/Controllers/TaskController.php
  ProcessMaker/Http/Middleware/GenerateMenus.php
  ProcessMaker/Traits/TaskControllerIndexMethods.php
  README.md
  devhub/pm-font/svg/arrow-left.svg
  devhub/pm-font/svg/box-arrow-up-right.svg
  devhub/pm-font/svg/inbox.svg
  devhub/pm-font/svg/tachometer-alt-average.svg
  resources/fonts/pm-font/index.html
  resources/fonts/pm-font/processmaker-font.css
  resources/fonts/pm-font/processmaker-font.eot
  resources/fonts/pm-font/processmaker-font.less
  resources/fonts/pm-font/processmaker-font.module.less
  resources/fonts/pm-font/processmaker-font.scss
  resources/fonts/pm-font/processmaker-font.styl
  resources/fonts/pm-font/processmaker-font.svg
  resources/fonts/pm-font/processmaker-font.symbol.svg
  resources/fonts/pm-font/processmaker-font.ttf
  resources/fonts/pm-font/processmaker-font.woff
  resources/fonts/pm-font/processmaker-font.woff2
  resources/fonts/pm-font/symbol.html
  resources/fonts/pm-font/unicode.html
  resources/img/launchpad-images/icons/Info.svg
  resources/img/launchpad-images/icons/Launchpad.svg
  resources/js/components/shared/ColumnChooser.vue
  resources/js/components/shared/EllipsisMenu.vue
  resources/js/components/shared/LaunchpadSettingsModal.vue
  resources/js/components/shared/PaginationTable.vue
  resources/js/processes-catalogue/components/Bookmark.vue
  resources/js/processes-catalogue/components/Process.vue
  resources/js/processes-catalogue/components/ProcessCollapseInfo.vue
  resources/js/processes-catalogue/components/ProcessHeaderStart.vue
  resources/js/processes-catalogue/components/ProcessInfo.vue
  resources/js/processes-catalogue/components/ProcessScreen.vue
  resources/js/processes-catalogue/components/ProcessTab.vue
  resources/js/processes-catalogue/components/mixins/ProcessesMixin.js
  resources/js/tasks/components/DashboardViewer.vue
  resources/js/tasks/components/ListMixin.js
  resources/js/tasks/components/ParticipantHomeScreen.vue
  resources/js/tasks/components/ProcessesDashboardsMenu.vue
  resources/js/tasks/index.js
  resources/js/tasks/mixins/TasksMixin.js
  resources/js/tasks/router.js
  resources/views/processes-catalogue/index.blade.php
  resources/views/processes-catalogue/mobile.blade.php
  resources/views/tasks/index.blade.php
  routes/web.php
  tests/Feature/Api/UserConfigurationTest.php
  webpack.mix.js
Labels: 4.14.0

#8073 FOUR-21957: Completed forms in Cases do not show the data that was filled out in task
  ProcessMaker/Http/Controllers/RequestController.php
Labels: 4.14.0, RC1

#7957 FOUR-21398: [42359] - Update a Process Request (PUT METHOD API)
  ProcessMaker/Models/ProcessRequest.php
  tests/Feature/Api/ProcessRequestsTest.php
Labels: PO Backlog Bug, 4.14.0

#8047 Optimize Screens Data-Loading to Prevent Unnecessary Reloads
  resources/js/processes/screens/components/ScreenListing.vue
Labels: 4.14.0

#7952 FOUR-20331 Implement Saved Search Improvements use VarFinder
  .cursorrules
  ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php
  config/l5-swagger.php
  routes/v1_1/api.php
  tests/Feature/Api/UsersTest.php
  tests/Feature/Api/V1_1/ProcessVariableControllerTest.php
Labels: failing, 4.14.0

#7982 FOUR-21021 Add custom labels for metrics
  ProcessMaker/Facades/Metrics.php
  ProcessMaker/Jobs/CompleteActivity.php
  ProcessMaker/Jobs/RunScriptTask.php
  ProcessMaker/Listeners/BpmnSubscriber.php
  ProcessMaker/Services/MetricsService.php
  tests/Feature/Metrics/TaskMetricsTest.php
  tests/unit/MetricsServiceTest.php
  upgrades/2025_02_03_191354_clear_prometheus_metrics.php
Labels: 4.14.0, Beta1

#8077 FOUR-21936: Error 404 when importing old processes with sub processes
  ProcessMaker/Http/Controllers/Api/ProcessController.php
Labels: 4.14.0, Alpha3

#8080 observation/FOUR-22387: Route [package.savedsearch.defaults.edit] not defined
  resources/views/tasks/index.blade.php
Labels: 4.14.0, Beta2

#8068 FOUR-22148: The ellipsis in the column task is always showing
  resources/jscomposition/base/table/BaseTable.vue
  resources/jscomposition/base/table/TCell.vue
  resources/jscomposition/system/table/cell/truncatedGroupOptionsCell/TruncatedGroupOptionsCell.vue
Labels: 4.14.0, Beta2

#8085 FOUR-23123:The "Pan Tool" disappears when you press the keyboard "space" in the overview.
  resources/jscomposition/cases/casesDetail/components/NewOverview.vue
Labels: 4.14.0, Beta3

#8082 FOUR-22121 Support for REDIS_PREFIX
  .env.example
  ProcessMaker/Cache/CacheManagerBase.php
  config/cache.php
  tests/Feature/Cache/SettingCacheTest.php
Labels: 4.14.0, Beta3

#8081 FOUR-22186: The values in select list with Data connector or collection are not visible in Windows pane
  resources/js/requests/components/screenPreview.vue
Labels: 4.14.0, Beta3

#8089 FOUR-23139 - Fix SAML configuration
  ProcessMaker/Providers/ProcessMakerServiceProvider.php
  ProcessMaker/Repositories/SettingsConfigRepository.php
Labels: 4.14.0, Beta3

#8086 FOUR-22499 the searcher and pagination of the start new case are not working
  ProcessMaker/Http/Controllers/Api/ProcessController.php
  tests/Feature/Api/ProcessControllerTest.php
Labels: 4.14.0, Beta3

#8087 Observation/FOUR-22497: Processes list is not displayed in the home page
  ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php
  resources/js/tasks/components/ProcessesDashboardsMenu.vue
  routes/api.php
Labels: 4.14.0, Beta3

#8084 FOUR-23124 : Notification messages are not displayed correctly in different pages
  resources/js/notifications/components/notification-item.vue
Labels: 4.14.0, Beta3

#8088 FOUR-22623: White space in new-request-modal-pagination
  resources/views/tasks/index.blade.php
Labels: 4.14.0, Beta3

#8093 FOUR-23374
  database/migrations/2025_03_17_142216_add_default_value_for_properties_in_process_launchpad_table.php
Labels: 4.14.0, Beta4

#8092 FOUR-22425:Open launch pad remains stuck in alternatives even though Launch pad settings have already been configured
  resources/js/components/shared/LaunchpadSettingsModal.vue
Labels: 4.14.0, Beta4

#8101 observation/FOUR-23373 Different message is displayed instead of `Added successfully to bundle`
  resources/js/admin/auth-clients/components/AuthClientsListing.vue
  resources/js/components/shared/AddToBundle.vue
Labels: 4.14.0, Beta4

#8100 observation/FOUR-23375 Verify the actual route of devlink sidebar
  resources/js/admin/devlink/components/BundleContent.vue
Labels: 4.14.0, Beta4

#8094 Observation/FOUR-23367: Deleted dashboards continue to display on Home screen
  ProcessMaker/Http/Controllers/HomeController.php
Labels: 4.14.0, Beta5

#8106 FOUR-22703
  resources/js/tasks/edit.js
Labels: 4.14.0, Beta5

#8112 Resolve Process Creation Error for Templates with Signal Events
  ProcessMaker/Http/Controllers/Api/TemplateController.php
Labels: 4.14.0, Beta6

#8113 FOUR-22381: The Email is not arriving an error in the 4.14 Beta3
  ProcessMaker/Mail/TaskActionByEmail.php
Labels: 4.14.0, Beta6

#8110 FOUR-22636: Cloned tasks with notifications have Assigned and due by default, even when these have been modified
  ProcessMaker/Models/Process.php
  resources/js/processes/modeler/components/inspector/TaskNotifications.vue
Labels: 4.14.0, Beta7

#8117 Observation/FOUR-23539: Process list showing system processes
  ProcessMaker/Http/Controllers/Api/ProcessLaunchpadController.php
  resources/js/tasks/components/ProcessesDashboardsMenu.vue
Labels: 4.14.0, Beta7

#8109 The "Create your missing assets with AI" message is not displayed when a process is generated with AI Assistant from a project.
  resources/js/processes/components/CreateProcessModal.vue
Labels: 4.14.0, Beta7

#8095 observation/FOUR-23376 `Add to bundle` option is not displayed in the Dashboards and Menus tabs
  resources/js/components/shared/AddToBundle.vue
Labels: 4.14.0, Beta7

#8118 FOUR-23512 Data in 'Available columns' is saved without 'data.' in Saved search by default
  ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php
Labels: 4.14.0, Beta7

#8120 Bugfix/FOUR-23515: Columns that do not belong to the saved search are listed in available columns
  ProcessMaker/Http/Controllers/Api/V1_1/ProcessVariableController.php
  tests/Feature/Api/V1_1/ProcessVariableControllerTest.php
Labels: 4.14.0

#8115 FOUR-22377 SettingCache for null values
  ProcessMaker/Cache/CacheManagerBase.php
  ProcessMaker/Cache/Settings/SettingCacheManager.php
  tests/Feature/Cache/CacheManagerBaseTest.php
  tests/Feature/Cache/SettingCacheTest.php
Labels: 4.14.0, Beta7

#8123 FOUR-23550: The configure size columns configuration is not keep
  resources/jscomposition/base/table/BaseTable.vue
  resources/jscomposition/base/table/THeader.vue
  resources/jscomposition/base/table/composables/columnComposable.js
  resources/jscomposition/cases/casesMain/App.vue
  resources/jscomposition/cases/casesMain/CasesDataSection.vue
  resources/jscomposition/cases/casesMain/api/index.js
  resources/jscomposition/cases/casesMain/main.js
  resources/jscomposition/cases/casesMain/store/index.js
  resources/jscomposition/cases/casesMain/store/store.js
  resources/jscomposition/cases/casesMain/variables/index.js
  resources/jscomposition/system/table/FilterableTable.vue
Labels: 4.14.0, Beta7

#8129 FOUR-23606 - Remove unnecessary caching that was bypassing the framework
  ProcessMaker/Observers/SettingObserver.php
Labels: 4.14.0, Beta8

#8125 observation/FOUR-23561 DevLink > Search icon is overlapped by the word in the search field
  resources/js/admin/devlink/components/AssetListing.vue
Labels: 4.14.0, Beta8

#8121 Observation/FOUR-23536: Chart configured in launchpad settings is lost after pressing Info button
  resources/js/processes-catalogue/components/BaseChart.vue
Labels: 4.14.0, Beta8

#8119 FOUR-22891 - Fix reset to default columns
  resources/js/components/shared/ColumnChooser.vue
  resources/js/tasks/components/TasksList.vue
  resources/js/tasks/components/defaultTaskColumns.js
Labels: 4.14.0, Beta8

#8130 FOUR-23614 - Fix dev link nullable column
  database/migrations/2025_03_24_223125_make_dev_links_client_secret_nullable.php
Labels: 4.14.0, Beta8

#8132 Bugfix/FOUR-23621: Error in console when clicking on the Cases tab; no cases displayed
  ProcessMaker/Http/Controllers/Api/UserConfigurationController.php
  resources/jscomposition/cases/casesMain/CasesDataSection.vue
Labels: RC2, 4.14.0

#8134 FOUR-23552: Checking some SSO options is not working correctly.
  ProcessMaker/Cache/Settings/SettingCacheManager.php
  tests/Feature/Cache/SettingCacheTest.php
Labels: RC1, 4.14.1

#8140 FOUR-23649: Updated JSON encoding to native array format for better data handling.
  database/factories/ProcessMaker/Models/ProcessVersionFactory.php
  tests/Feature/Api/ScreenTest.php
Labels: RC2, 4.14.1

#8133 FOUR-22470: It is not possible to reopen a template that was created in base a process with launch pad
  ProcessMaker/Templates/ProcessTemplate.php
Labels: RC1, 4.14.1

#8141 FOUR-23518 timeout issue in script microservice fails after 30 seconds
  ProcessMaker/ScriptRunners/ScriptMicroserviceRunner.php
Labels: RC1, 4.14.1

#8135 Observation/FOUR-23548: Edit Task Column form grows in length when a screen is set to launchpad
  resources/js/components/shared/ColumnChooser.vue
Labels: RC1, 4.14.1

#8145 Set specific versions to allow for package-plaid
  composer.json
  composer.lock
Labels: RC1, 4.14.1

#8136 FOUR-23556: VarFinder Panel Not Displaying on Cases and Analytics Pages
  resources/views/layouts/layoutnext.blade.php
Labels: RC1, 4.14.1

#8144 FOUR-23140: Case title column does not have the Reset table option
  resources/jscomposition/base/table/BaseTable.vue
  resources/jscomposition/cases/casesMain/config/columns.js
Labels: RC1, 4.14.1

#8138 FOUR-23520: Mobile view - Headers are not displayed in the first login
  ProcessMaker/Http/Controllers/HomeController.php
Labels: RC1, 4.14.1

#8150 observation/FOUR-23662: `Add asset to Bundle` modal does not display the correct name for a Decision Table
  resources/js/components/shared/AddToBundle.vue
Labels: RC1, 4.14.2

#8156 FOUR-23419: Implement new UI for new comments
  resources/js/tasks/api/index.js
  resources/js/tasks/components/TasksPreview.vue
  resources/js/tasks/components/taskPreview/TaskPreviewAssignment.vue
  resources/js/tasks/edit.js
  resources/js/tasks/variables/index.js
Labels: merge-epic
